[package]
name = "shpz"
edition = "2021"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Markus Moenig"]
description = "Shape Prozessing Language"
keywords = ["language", "voxel", "rendering", "procedural", "modeling"]
repository = "https://github.com/markusmoenig/Shape-Z.git"
homepage = "https://shape-z.com"

[dependencies]
# shapezlib = { version = "0.1.0" }
shapezlib = { version = "0.1.0", path = "../shapezlib" }
clap = "4.1.5"
notify = "8.1.0"
