use crate::prelude::*;
use rayon::prelude::*;

#[derive(Clone)]
pub struct SegmentationState {
    pub bbox: Aabb<f32>,
    pub plane: Plane,
    pub u: Value,
    pub v: Value,
    pub d: Value,
    pub sdf: Value,
    pub inside: Value,
}

#[derive(Clone)]
pub struct Execution {
    /// Global variables. The parser keeps count of all global variables and we allocate the array on creation.
    pub globals: Vec<Value>,

    /// Local variables used inside function bodies.
    locals: Vec<Value>,

    /// The world coordinate of the current voxel
    pub world: Value,
    /// The segment transformed local coordinate
    pub local: Value,
    /// The segment computed u value
    pub u: Value,
    /// The segment computed v value
    pub v: Value,
    /// The segment computed d (depth) value
    pub d: Value,
    /// The current plane
    pub plane: Plane,
    /// The shape computed distance value
    pub sdf: Value,
    /// -sdf
    pub inside: Value,

    /// The current segmentation state
    state_stack: Vec<SegmentationState>,

    /// The locals state for recursive functions
    locals_stack: Vec<Vec<Value>>,

    /// Hash, generated by patterns and passed on to the materials.
    pub hash: f32,

    /// The current bbox of the model space. Gets subdivided by segments during
    /// execution.
    pub bbox: Aabb<f32>,

    /// The material the VM writes to.
    pub material: BSDFMaterial,

    /// The execution stack.
    pub stack: Vec<Value>,

    /// Function return value.
    return_value: Option<Value>,

    /// Heightmap of the current terrain shape (for slope evaluation)
    terrain_heightmap: Option<Arc<Vec<NodeOp>>>,
}

impl Execution {
    pub fn new(var_size: usize) -> Self {
        Self {
            globals: vec![Value::zero(); var_size],
            locals: vec![],
            world: Value::zero(),
            local: Value::zero(),
            u: Value::zero(),
            v: Value::zero(),
            d: Value::zero(),
            plane: Plane::XZ,
            sdf: Value::zero(),
            inside: Value::zero(),
            state_stack: Vec::with_capacity(8),
            locals_stack: vec![],
            hash: 1.0,
            bbox: Aabb {
                min: Vec3::zero(),
                max: Vec3::one(),
            },
            material: BSDFMaterial::default(),
            stack: Vec::with_capacity(32),
            return_value: None,
            terrain_heightmap: None,
        }
    }

    pub fn new_from_var(execution: &Execution) -> Self {
        Self {
            globals: execution.globals.clone(),
            locals: vec![],
            world: Value::zero(),
            local: Value::zero(),
            u: Value::zero(),
            v: Value::zero(),
            d: Value::zero(),
            plane: Plane::XZ,
            sdf: Value::zero(),
            inside: Value::zero(),
            state_stack: Vec::with_capacity(8),
            locals_stack: vec![],
            hash: 1.0,
            bbox: Aabb {
                min: Vec3::zero(),
                max: Vec3::one(),
            },
            material: BSDFMaterial::default(),
            stack: Vec::with_capacity(32),
            return_value: None,
            terrain_heightmap: None,
        }
    }

    pub fn execute(&mut self, code: &[NodeOp], program: &mut Program) {
        for op in code {
            // Unwind if return is set
            if self.return_value.is_some() {
                break;
            }
            match op {
                NodeOp::LoadGlobal(index) => {
                    self.stack.push(self.globals[*index]);
                }
                NodeOp::StoreGlobal(index) => {
                    self.globals[*index] = self.stack.pop().unwrap();
                }
                NodeOp::LoadLocal(index) => {
                    self.stack.push(self.locals[*index]);
                }
                NodeOp::StoreLocal(index) => {
                    self.locals[*index] = self.stack.pop().unwrap();
                }
                NodeOp::Swap => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(b);
                    self.stack.push(a);
                }
                NodeOp::GetComponents(swizzle) => {
                    let v = self.stack.pop().unwrap();
                    let mut result = vec![];

                    for &index in swizzle {
                        let f = match index {
                            0 => v.x(),
                            1 => v.y(),
                            2 => v.z(),
                            _ => continue,
                        };
                        result.push(f);
                    }

                    // Push as single Value: scalar or vector depending on result length
                    let pushed = match result.as_slice() {
                        [x] => Value::from_float(*x),
                        [x, y] => Value::from_vec2(Vec2::new(*x, *y)),
                        [x, y, z] => Value::from_vec3(Vec3::new(*x, *y, *z)),
                        _ => Value::from_float(0.0),
                    };

                    self.stack.push(pushed);
                }
                NodeOp::SetComponents(swizzle) => {
                    let value = self.stack.pop().unwrap();
                    let mut target = self.stack.pop().unwrap();

                    let components = match swizzle.len() {
                        1 => vec![value.x()],
                        2 => vec![value.x(), value.y()],
                        3 => vec![value.x(), value.y(), value.z()],
                        _ => vec![],
                    };

                    for (i, &idx) in swizzle.iter().enumerate() {
                        if i >= components.len() {
                            break;
                        }
                        match idx {
                            0 => target.0[0] = components[i],
                            1 => target.0[1] = components[i],
                            2 => target.0[2] = components[i],
                            _ => {}
                        }
                    }

                    self.stack.push(target);
                }
                NodeOp::Push(v) => self.stack.push(*v),
                NodeOp::Clear => _ = self.stack.pop(),
                NodeOp::FunctionCall(arity, total_locals, index) => {
                    self.push_locals_state();
                    self.locals = vec![Value::zero(); *total_locals as usize];

                    // Arguments are on stack in call order
                    for index in (0..*arity as usize).rev() {
                        if let Some(arg) = self.stack.pop() {
                            self.locals[index] = arg;
                        }
                    }

                    // Save the stack position
                    let stack_base = self.stack.len();

                    // Execute the function body
                    let body = program.user_functions[*index].clone(); // Arc clone
                    self.execute(&body, program);

                    // Retrieve the return value. A function always returns exactly one value.
                    let ret = if self.return_value.is_some() {
                        self.return_value.take().unwrap_or(Value::zero())
                    } else if self.stack.len() > stack_base {
                        self.stack.pop().unwrap()
                    } else {
                        Value::zero()
                    };

                    // Clean up temporaries
                    while self.stack.len() > stack_base {
                        _ = self.stack.pop();
                    }

                    self.pop_locals_state();

                    // Push the return value
                    self.stack.push(ret);
                }
                NodeOp::Recursive(depth, body) => {
                    let mut max_depth = 1;
                    if depth.is_empty() {
                        self.execute(depth, program);
                        if let Some(value) = self.stack.last() {
                            max_depth = value.as_float() as i32;
                        }
                    }
                    self.push_state();
                    for level in 0..max_depth {
                        self.execute(body, program);
                    }
                    self.pop_state();
                }
                NodeOp::Return => {
                    // Prefer the top of stack as the explicit return expression.
                    // If nothing was pushed (e.g., miscompiled branch), fall back to an
                    // existing return_value (from a deeper recursive call), else zero.
                    let v = if let Some(top) = self.stack.pop() {
                        top
                    } else if let Some(prev) = self.return_value.take() {
                        prev
                    } else {
                        Value::zero()
                    };
                    self.return_value = Some(v);
                    break;
                }
                NodeOp::Pack2 => {
                    let y = self.stack.pop().unwrap();
                    let x = self.stack.pop().unwrap();
                    self.stack.push(Value::from_components(x.x(), y.x(), 0.0));
                }
                NodeOp::Pack3 => {
                    let z = self.stack.pop().unwrap();
                    let y = self.stack.pop().unwrap();
                    let x = self.stack.pop().unwrap();
                    self.stack.push(Value::from_components(x.x(), y.x(), z.x()));
                }
                NodeOp::Dup => {
                    if let Some(top) = self.stack.last() {
                        self.stack.push(top.clone());
                    }
                }
                NodeOp::If(then_code, else_code) => {
                    let value = self.stack.pop().unwrap().truthy();
                    if value {
                        self.execute(then_code, program);
                    } else if let Some(else_code) = else_code {
                        self.execute(else_code, program);
                    }
                }
                NodeOp::IfClear(code) => {
                    if self.stack.is_empty() {
                        self.execute(code, program);
                    }
                }
                NodeOp::Place(id, at_code) => {
                    let mut at = Vec3::zero();
                    if !at_code.is_empty() {
                        self.execute(at_code, program);
                        if let Some(rc) = self.stack.pop() {
                            at = rc.as_vec3();
                        }
                    }
                    self.place(id, at, program);
                }
                NodeOp::World => {
                    self.stack.push(self.world);
                }
                NodeOp::Local => {
                    self.stack.push(self.local);
                }
                NodeOp::U => {
                    self.stack.push(self.u);
                }
                NodeOp::V => {
                    self.stack.push(self.v);
                }
                NodeOp::D => {
                    self.stack.push(self.d);
                }
                NodeOp::SDF => {
                    self.stack.push(self.sdf);
                }
                NodeOp::Inside => {
                    self.stack.push(self.inside);
                }
                NodeOp::Hash => {
                    self.stack.push(Value::from_float(self.hash));
                }
                // Math
                NodeOp::Add => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.add(b));
                }
                NodeOp::Sub => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.sub(b));
                }
                NodeOp::Mul => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.mul(b));
                }
                NodeOp::Div => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.div(b));
                }
                NodeOp::Length => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.length());
                }
                NodeOp::Abs => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.abs());
                }
                NodeOp::Sin => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.sin());
                }
                NodeOp::Cos => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.cos());
                }
                NodeOp::Normalize => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.normalize());
                }
                NodeOp::Tan => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.tan());
                }
                NodeOp::Atan => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.atan());
                }
                NodeOp::Atan2 => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.atan2(b));
                }
                NodeOp::Dot => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.dot(b));
                }
                NodeOp::Cross => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.cross(b));
                }
                NodeOp::Floor => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_float(a.as_float().floor()));
                }
                NodeOp::Ceil => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_float(a.as_float().ceil()));
                }
                NodeOp::Fract => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_float(a.as_float().fract()));
                }
                NodeOp::Mod => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_float(a.as_float() % b.as_float()));
                }
                NodeOp::Radians => {
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_float(a.as_float().to_radians()));
                }
                NodeOp::Degrees => {
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_float(a.as_float().to_degrees()));
                }
                NodeOp::Min => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.min(b));
                }
                NodeOp::Max => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.max(b));
                }
                NodeOp::Mix => {
                    let c: Value = self.stack.pop().unwrap();
                    let b: Value = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.mix(b, c));
                }
                NodeOp::Smoothstep => {
                    let c: Value = self.stack.pop().unwrap();
                    let b: Value = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.smoothstep(b, c));
                }
                NodeOp::Step => {
                    let b: Value = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.step(b));
                }
                NodeOp::Clamp => {
                    let c: Value = self.stack.pop().unwrap();
                    let b: Value = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.clamp(b, c));
                }
                NodeOp::Sqrt => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.sqrt());
                }
                NodeOp::Log => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.log());
                }
                NodeOp::Pow => {
                    let a = self.stack.pop().unwrap();
                    let b: Value = self.stack.pop().unwrap();
                    self.stack.push(a.pow(b));
                }
                NodeOp::SmoothUnion => {
                    let c: Value = self.stack.pop().unwrap();
                    let b: Value = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_float(self.smooth_min(
                        a.as_float(),
                        b.as_float(),
                        c.as_float(),
                    )));
                }
                NodeOp::WhiteNoise => {
                    let val = self.white_noise();
                    self.stack.push(Value::from_float(val));
                }
                NodeOp::ValueNoise => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    let val = self.value_noise(a.as_float() as i32, b.as_vec3());
                    self.hash = val;
                    self.stack.push(Value::from_float(val));
                }
                // Comparison
                NodeOp::Eq => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() == b.x()));
                }
                NodeOp::Ne => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() != b.x()));
                }
                NodeOp::Lt => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() < b.x()));
                }
                NodeOp::Le => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() <= b.x()));
                }
                NodeOp::Gt => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() > b.x()));
                }
                NodeOp::Ge => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() >= b.x()));
                }
                // Logical
                NodeOp::And => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_bool(a.x() != 0.0 && b.x() != 0.0));
                }
                NodeOp::Or => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_bool(a.x() != 0.0 || b.x() != 0.0));
                }
                // Unary
                NodeOp::Not => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() == 0.0));
                }
                NodeOp::Neg => {
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_components(-a.x(), -a.y(), -a.z()));
                }
                NodeOp::PointAt => {
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_vec3(self.point_at(a.as_vec3())));
                }
                NodeOp::Print => {
                    let a = self.stack.pop().unwrap();
                    println!("print: {:?}", a);
                }
                // Shapes
                NodeOp::ShapeRect(at, size, body) => {
                    self.push_state();

                    let bb_size = self.bbox.size();
                    let bbox_size = match self.plane {
                        Plane::XY => Vec2::new(bb_size.w, bb_size.h),
                        Plane::XZ => Vec2::new(bb_size.w, bb_size.d),
                        Plane::YZ => Vec2::new(bb_size.h, bb_size.d),
                        Plane::ZY => Vec2::new(bb_size.d, bb_size.h),
                    };

                    // Evaluate rect size
                    let mut dims = bbox_size;
                    if !size.is_empty() {
                        self.execute(size, program);
                        dims = self.stack.pop().unwrap().as_vec2();
                    }

                    // Evaluate anchor (at)
                    let mut anchor = Vec2::broadcast(0.5);
                    if !at.is_empty() {
                        self.execute(at, program);
                        anchor = self.stack.pop().unwrap().as_vec2();
                    }

                    anchor.x = anchor.x.clamp(0.0, 1.0);
                    anchor.y = anchor.y.clamp(0.0, 1.0);

                    match self.plane {
                        Plane::XY => {
                            let plane_min = Vec2::new(self.bbox.min.x, self.bbox.min.y);
                            let rect_min = plane_min + anchor * (bbox_size - dims);

                            self.bbox.min.x = rect_min.x;
                            self.bbox.min.y = rect_min.y;
                            self.bbox.max.x = rect_min.x + dims.x;
                            self.bbox.max.y = rect_min.y + dims.y;
                        }
                        Plane::XZ => {
                            let plane_min = Vec2::new(self.bbox.min.x, self.bbox.min.z);
                            let rect_min = plane_min + anchor * (bbox_size - dims);

                            self.bbox.min.x = rect_min.x;
                            self.bbox.min.z = rect_min.y;
                            self.bbox.max.x = rect_min.x + dims.x;
                            self.bbox.max.z = rect_min.y + dims.y;
                        }
                        Plane::YZ => {
                            let plane_min = Vec2::new(self.bbox.min.y, self.bbox.min.z);
                            let rect_min = plane_min + anchor * (bbox_size - dims);

                            self.bbox.min.y = rect_min.x;
                            self.bbox.min.z = rect_min.y;
                            self.bbox.max.y = rect_min.x + dims.x;
                            self.bbox.max.z = rect_min.y + dims.y;
                        }
                        Plane::ZY => {
                            let plane_min = Vec2::new(self.bbox.min.z, self.bbox.min.y);
                            let rect_min = plane_min + anchor * (bbox_size - dims);

                            self.bbox.min.z = rect_min.x;
                            self.bbox.min.y = rect_min.y;
                            self.bbox.max.z = rect_min.x + dims.x;
                            self.bbox.max.y = rect_min.y + dims.y;
                        }
                    }

                    // Execute body if local point is within new bbox
                    if self.bbox.contains_point(self.local.as_vec3()) {
                        let local = self.local.as_vec3();

                        let p = match self.plane {
                            Plane::XY => Vec2::new(
                                local.x - (self.bbox.min.x + dims.x * 0.5),
                                local.y - (self.bbox.min.y + dims.y * 0.5),
                            ),
                            Plane::XZ => Vec2::new(
                                local.x - (self.bbox.min.x + dims.x * 0.5),
                                local.z - (self.bbox.min.z + dims.y * 0.5),
                            ),
                            Plane::YZ => Vec2::new(
                                local.y - (self.bbox.min.y + dims.x * 0.5),
                                local.z - (self.bbox.min.z + dims.y * 0.5),
                            ),
                            Plane::ZY => Vec2::new(
                                local.z - (self.bbox.min.z + dims.x * 0.5),
                                local.y - (self.bbox.min.y + dims.y * 0.5),
                            ),
                        };

                        let sdf = self.sdf_box(p, dims * 0.5, 0.0);
                        self.sdf = Value::from_float(sdf);
                        self.inside = Value::from_float(-sdf);

                        self.execute(body, program);
                    }

                    self.pop_state();
                }
                NodeOp::ShapeTerrain(at, heightmap, body) => {
                    self.push_state();

                    self.plane = Plane::XZ;

                    let bb_size = self.bbox.size();
                    let bbox_size = match self.plane {
                        Plane::XY => Vec2::new(bb_size.w, bb_size.h),
                        Plane::XZ => Vec2::new(bb_size.w, bb_size.d),
                        Plane::YZ => Vec2::new(bb_size.h, bb_size.d),
                        Plane::ZY => Vec2::new(bb_size.d, bb_size.h),
                    };

                    let dims = bbox_size;

                    // Evaluate anchor (at)
                    let mut anchor = Vec2::broadcast(0.5);
                    if !at.is_empty() {
                        self.execute(at, program);
                        anchor = self.stack.pop().unwrap().as_vec2();
                    }

                    anchor.x = anchor.x.clamp(0.0, 1.0);
                    anchor.y = anchor.y.clamp(0.0, 1.0);

                    match self.plane {
                        Plane::XY => {
                            let plane_min = Vec2::new(self.bbox.min.x, self.bbox.min.y);
                            let rect_min = plane_min + anchor * (bbox_size - dims);

                            self.bbox.min.x = rect_min.x;
                            self.bbox.min.y = rect_min.y;
                            self.bbox.max.x = rect_min.x + dims.x;
                            self.bbox.max.y = rect_min.y + dims.y;
                        }
                        Plane::XZ => {
                            let plane_min = Vec2::new(self.bbox.min.x, self.bbox.min.z);
                            let rect_min = plane_min + anchor * (bbox_size - dims);

                            self.bbox.min.x = rect_min.x;
                            self.bbox.min.z = rect_min.y;
                            self.bbox.max.x = rect_min.x + dims.x;
                            self.bbox.max.z = rect_min.y + dims.y;
                        }
                        Plane::YZ => {
                            let plane_min = Vec2::new(self.bbox.min.y, self.bbox.min.z);
                            let rect_min = plane_min + anchor * (bbox_size - dims);

                            self.bbox.min.y = rect_min.x;
                            self.bbox.min.z = rect_min.y;
                            self.bbox.max.y = rect_min.x + dims.x;
                            self.bbox.max.z = rect_min.y + dims.y;
                        }
                        Plane::ZY => {
                            let plane_min = Vec2::new(self.bbox.min.z, self.bbox.min.y);
                            let rect_min = plane_min + anchor * (bbox_size - dims);

                            self.bbox.min.z = rect_min.x;
                            self.bbox.min.y = rect_min.y;
                            self.bbox.max.z = rect_min.x + dims.x;
                            self.bbox.max.y = rect_min.y + dims.y;
                        }
                    }

                    // Execute body if local point is within new bbox
                    if self.bbox.contains_point(self.local.as_vec3()) {
                        let local = self.local.as_vec3();

                        // let p = match self.plane {
                        //     Plane::XY => Vec2::new(
                        //         local.x - (self.bbox.min.x + dims.x * 0.5),
                        //         local.y - (self.bbox.min.y + dims.y * 0.5),
                        //     ),
                        //     Plane::XZ => Vec2::new(
                        //         local.x - (self.bbox.min.x + dims.x * 0.5),
                        //         local.z - (self.bbox.min.z + dims.y * 0.5),
                        //     ),
                        //     Plane::YZ => Vec2::new(
                        //         local.y - (self.bbox.min.y + dims.x * 0.5),
                        //         local.z - (self.bbox.min.z + dims.y * 0.5),
                        //     ),
                        //     Plane::ZY => Vec2::new(
                        //         local.z - (self.bbox.min.z + dims.x * 0.5),
                        //         local.y - (self.bbox.min.y + dims.y * 0.5),
                        //     ),
                        // };

                        self.u = Value::from_float(local.x - self.bbox.min.x);
                        self.v = Value::from_float(local.z - self.bbox.min.z);

                        self.execute(&heightmap, program);

                        let mut h = 0.0;
                        if let Some(height) = self.stack.pop() {
                            h = height.x();
                        }

                        let d = local.y - h;
                        self.d = Value::from_float(d);
                        self.sdf = self.d;
                        self.inside = Value::from_float(-d);

                        self.terrain_heightmap = Some(heightmap.clone());
                        self.execute(body, program);
                        self.terrain_heightmap = None;
                    }

                    self.pop_state();
                }
                NodeOp::Slope => {
                    let eps = self.stack.pop().unwrap().as_float() * 1.0
                        / program.grid.read().unwrap().density_f;

                    // If no heightmap is active
                    if self.terrain_heightmap.is_none() {
                        self.stack.push(Value::from_float(0.0));
                        continue;
                    }

                    let pos = self.local.as_vec3();
                    // Compute four offset positions in the current plane
                    let (px1, px0, py1, py0) = match self.plane {
                        Plane::XY => (
                            Vec3::new(pos.x + eps, pos.y, pos.z),
                            Vec3::new(pos.x - eps, pos.y, pos.z),
                            Vec3::new(pos.x, pos.y + eps, pos.z),
                            Vec3::new(pos.x, pos.y - eps, pos.z),
                        ),
                        Plane::XZ => (
                            Vec3::new(pos.x + eps, pos.y, pos.z),
                            Vec3::new(pos.x - eps, pos.y, pos.z),
                            Vec3::new(pos.x, pos.y, pos.z + eps),
                            Vec3::new(pos.x, pos.y, pos.z - eps),
                        ),
                        Plane::YZ => (
                            Vec3::new(pos.x, pos.y + eps, pos.z),
                            Vec3::new(pos.x, pos.y - eps, pos.z),
                            Vec3::new(pos.x, pos.y, pos.z + eps),
                            Vec3::new(pos.x, pos.y, pos.z - eps),
                        ),
                        Plane::ZY => (
                            Vec3::new(pos.x, pos.y, pos.z + eps),
                            Vec3::new(pos.x, pos.y, pos.z - eps),
                            Vec3::new(pos.x, pos.y + eps, pos.z),
                            Vec3::new(pos.x, pos.y - eps, pos.z),
                        ),
                    };

                    let old_local = self.local;
                    let mut hx1: f32 = 0.0;
                    let mut hx0: f32 = 0.0;
                    let mut hy1: f32 = 0.0;
                    let mut hy0: f32 = 0.0;

                    if let Some(heightmap) = &self.terrain_heightmap.clone() {
                        let code = &heightmap;
                        // Sample at (pos + eps in x)
                        self.local = Value::from_vec3(px1);
                        self.execute(code, program);
                        if let Some(height) = self.stack.pop() {
                            hx1 = height.as_float();
                        }
                        // Sample at (pos - eps in x)
                        self.local = Value::from_vec3(px0);
                        self.execute(code, program);
                        if let Some(height) = self.stack.pop() {
                            hx0 = height.as_float();
                        }
                        // Sample at (pos + eps in y)
                        self.local = Value::from_vec3(py1);
                        self.execute(code, program);
                        if let Some(height) = self.stack.pop() {
                            hy1 = height.as_float();
                        }
                        // Sample at (pos - eps in y)
                        self.local = Value::from_vec3(py0);
                        self.execute(code, program);
                        if let Some(height) = self.stack.pop() {
                            hy0 = height.as_float();
                        }
                    }

                    self.local = old_local;

                    let dx = (hx1 - hx0) / (2.0 * eps);
                    let dy = (hy1 - hy0) / (2.0 * eps);
                    let tan_theta = (dx * dx + dy * dy).sqrt();

                    self.stack.push(Value::from_float(tan_theta));
                }
                NodeOp::ShapeDisc(at, radius, body) => {
                    self.push_state();

                    let mut r = 1.0;
                    if !radius.is_empty() {
                        self.execute(radius, program);
                        r = self.stack.pop().unwrap().as_float();
                    }

                    // 0.0 = flush with min side, 0.5 = centred, 1.0 = flush with max side.
                    let mut anchor = Vec2::broadcast(0.5);
                    if !at.is_empty() {
                        self.execute(at, program);
                        anchor = self.stack.pop().unwrap().as_vec2();
                    }
                    anchor.x = anchor.x.clamp(0.0, 1.0);
                    anchor.y = anchor.y.clamp(0.0, 1.0);

                    let bb_size = self.bbox.size();
                    let (plane_min, plane_size) = match self.plane {
                        Plane::XY => (
                            Vec2::new(self.bbox.min.x, self.bbox.min.y),
                            Vec2::new(bb_size.w, bb_size.h),
                        ),
                        Plane::XZ => (
                            Vec2::new(self.bbox.min.x, self.bbox.min.z),
                            Vec2::new(bb_size.w, bb_size.d),
                        ),
                        Plane::YZ => (
                            Vec2::new(self.bbox.min.y, self.bbox.min.z),
                            Vec2::new(bb_size.h, bb_size.d),
                        ),
                        Plane::ZY => (
                            Vec2::new(self.bbox.min.z, self.bbox.min.y),
                            Vec2::new(bb_size.d, bb_size.h),
                        ),
                    };

                    let offset = plane_min
                        + anchor * (plane_size - Vec2::broadcast(2.0 * r))
                        + Vec2::broadcast(r);

                    match self.plane {
                        Plane::XY => {
                            self.bbox.min.x = offset.x - r;
                            self.bbox.max.x = offset.x + r;
                            self.bbox.min.y = offset.y - r;
                            self.bbox.max.y = offset.y + r;
                        }
                        Plane::XZ => {
                            self.bbox.min.x = offset.x - r;
                            self.bbox.max.x = offset.x + r;
                            self.bbox.min.z = offset.y - r;
                            self.bbox.max.z = offset.y + r;
                        }
                        Plane::YZ => {
                            self.bbox.min.y = offset.x - r;
                            self.bbox.max.y = offset.x + r;
                            self.bbox.min.z = offset.y - r;
                            self.bbox.max.z = offset.y + r;
                        }
                        Plane::ZY => {
                            self.bbox.min.z = offset.x - r;
                            self.bbox.max.z = offset.x + r;
                            self.bbox.min.y = offset.y - r;
                            self.bbox.max.y = offset.y + r;
                        }
                    }

                    if self.bbox.contains_point(self.local.as_vec3()) {
                        let local = self.local.as_vec3();

                        let (p, h) = match self.plane {
                            Plane::XY => {
                                (Vec2::new(local.x - offset.x, local.y - offset.y), local.z)
                            }
                            Plane::XZ => {
                                (Vec2::new(local.x - offset.x, local.z - offset.y), local.y)
                            }
                            Plane::YZ => {
                                (Vec2::new(local.y - offset.x, local.z - offset.y), local.x)
                            }
                            Plane::ZY => {
                                (Vec2::new(local.z - offset.x, local.y - offset.y), local.x)
                            }
                        };

                        let theta = p.y.atan2(p.x);
                        let rlen = p.magnitude();
                        let sdf = rlen - r;

                        use std::f32::consts::TAU;

                        let repeats = 5.0;
                        let u = (theta / TAU * repeats + repeats * 0.5).fract();

                        self.u = Value::from_float(u);
                        self.v = Value::from_float(h.abs());
                        self.sdf = Value::from_float(sdf);
                        self.inside = Value::from_float(-sdf);

                        if sdf <= 0.0 {
                            self.execute(body, program);
                        }
                    }

                    self.pop_state();
                }
                // Segments
                NodeOp::SegmentLeft(depth, body) => {
                    self.push_state();

                    self.plane = Plane::ZY;
                    let local = self.local.as_vec3();

                    let thickness = if depth.is_empty() {
                        0.1
                    } else {
                        self.execute(depth, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.bbox.max.x = self.bbox.min.x + thickness;
                    if self.bbox.contains_point(local) {
                        self.u = Value::from_float(local.z - self.bbox.min.z); // u = Z
                        self.v = Value::from_float(local.y - self.bbox.min.y); // v = Y
                        self.d = Value::from_float(local.x - self.bbox.min.x); // d = X (depth)

                        self.execute(body, program);
                    }

                    self.pop_state();
                }
                NodeOp::SegmentBack(depth, body) => {
                    self.push_state();

                    self.plane = Plane::XY;
                    let local = self.local.as_vec3();

                    let thickness = if depth.is_empty() {
                        0.1
                    } else {
                        self.execute(depth, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.bbox.max.z = self.bbox.min.z + thickness;
                    if self.bbox.contains_point(local) {
                        self.u = Value::from_float(local.x - self.bbox.min.x); // u = X
                        self.v = Value::from_float(local.y - self.bbox.min.y); // v = Y
                        self.d = Value::from_float(local.z - self.bbox.min.z); // d = Z (depth)

                        self.execute(body, program);
                    }

                    self.pop_state();
                }
                NodeOp::SegmentFloor(depth, body) => {
                    self.push_state();

                    self.plane = Plane::XZ;
                    let local = self.local.as_vec3();

                    let thickness = if depth.is_empty() {
                        0.1
                    } else {
                        self.execute(depth, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.bbox.max.y = self.bbox.min.y + thickness;
                    if self.bbox.contains_point(local) {
                        self.u = Value::from_float(local.x - self.bbox.min.x); // u = X
                        self.v = Value::from_float(local.z - self.bbox.min.z); // v = Z
                        self.d = Value::from_float(local.y - self.bbox.min.y); // d = Y (depth from floor)

                        self.execute(body, program);
                    }

                    self.pop_state();
                }
                NodeOp::SegmentRight(depth, body) => {
                    self.push_state();

                    self.plane = Plane::ZY;
                    let local = self.local.as_vec3();

                    let thickness = if depth.is_empty() {
                        0.1
                    } else {
                        self.execute(depth, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.bbox.min.x = self.bbox.max.x - thickness;
                    if self.bbox.contains_point(local) {
                        self.u = Value::from_float(local.z - self.bbox.min.z); // u = Z
                        self.v = Value::from_float(local.y - self.bbox.min.y); // v = Y
                        self.d = Value::from_float(self.bbox.max.x - local.x); // d = X (depth)
                        self.execute(body, program);
                    }

                    self.pop_state();
                }
                NodeOp::SegmentFront(depth, body) => {
                    self.push_state();

                    self.plane = Plane::XY;
                    let local = self.local.as_vec3();

                    let thickness = if depth.is_empty() {
                        0.1
                    } else {
                        self.execute(depth, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.bbox.min.z = self.bbox.max.z - thickness;
                    if self.bbox.contains_point(local) {
                        self.u = Value::from_float(local.x - self.bbox.min.x); // u = X
                        self.v = Value::from_float(local.y - self.bbox.min.y); // v = Y
                        self.d = Value::from_float(self.bbox.max.z - local.z); // d = Z (depth)
                        self.execute(body, program);
                    }

                    self.pop_state();
                }
                NodeOp::SegmentCeiling(depth, body) => {
                    self.push_state();

                    self.plane = Plane::XZ;
                    let local = self.local.as_vec3();

                    let thickness = if depth.is_empty() {
                        0.1
                    } else {
                        self.execute(depth, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.bbox.min.y = self.bbox.max.y - thickness;
                    if self.bbox.contains_point(local) {
                        self.u = Value::from_float(local.x - self.bbox.min.x); // u = X
                        self.v = Value::from_float(local.z - self.bbox.min.z); // v = Z
                        self.d = Value::from_float(self.bbox.max.y - local.y); // d = Y (depth)
                        self.execute(body, program);
                    }

                    self.pop_state();
                }
                // Pattern
                NodeOp::PatternModulo(size, even, odd) => {
                    let u = self.u.as_float();
                    let v = self.v.as_float();

                    let modulo_size = if size.is_empty() {
                        0.02
                    } else {
                        self.execute(size, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    let cell_u = (u / modulo_size).floor() as i32;
                    let cell_v = (v / modulo_size).floor() as i32;

                    // Set `self.hash` based on cell ID
                    let cell_id = Vec2::new(cell_u as f32, cell_v as f32);
                    self.hash = (self.hash21(cell_id) + 1.0) * 0.5;

                    let is_even = (cell_u ^ cell_v) % 2 == 0;
                    if is_even {
                        if let Some(even) = even {
                            self.execute(even, program);
                        }
                    } else {
                        if let Some(odd) = odd {
                            self.execute(odd, program);
                        }
                    }
                }
                NodeOp::PatternBricks(size, gap, round, br, ce) => {
                    let brick_size = if size.is_empty() {
                        Vec2::new(0.3, 0.1)
                    } else {
                        self.execute(size, program);
                        self.stack.pop().unwrap().as_vec2()
                    };
                    let gap_size = if gap.is_empty() {
                        0.02
                    } else {
                        self.execute(gap, program);
                        self.stack.pop().unwrap().as_float()
                    };
                    let rounding = if round.is_empty() {
                        0.1
                    } else {
                        self.execute(round, program);
                        self.stack.pop().unwrap().as_float()
                    };
                    let cell = brick_size + Vec2::broadcast(gap_size);

                    let mut u = Vec2::new(self.u.x(), self.v.x()) / cell;
                    u.x += 0.5 * ((u.y.floor() as i32 % 2) as f32);

                    let cell_id = u.map(|v| v.floor());
                    self.hash = (self.hash21(cell_id) + 1.0) * 0.5;

                    let p = u.map(|v| v.fract()) - 0.5;
                    let rc = self.sdf_box(p, brick_size / cell * 0.5, rounding);

                    if rc < 0.0 {
                        if let Some(br) = br {
                            self.execute(br, program);
                        }
                    } else {
                        if let Some(ce) = ce {
                            self.execute(ce, program);
                        }
                    }
                }
                // Distance Functions
                NodeOp::DistanceSphere(at, radius, offset, scale, code) => {
                    let at = if at.is_empty() {
                        self.point_at(Vec3::zero())
                    } else {
                        self.execute(at, program);
                        let p = self.stack.pop().unwrap().as_vec3();
                        self.point_at(p)
                    };

                    let mut radius = if radius.is_empty() {
                        0.5
                    } else {
                        self.execute(radius, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.push_state();

                    let s = self.eval_profile_scale(scale, program);
                    if s != 1.0 {
                        radius *= s;
                    }

                    let sdf0 = (self.local.as_vec3() - at).magnitude() - radius;
                    let off = self.eval_profile_offset(offset, program);
                    let sdf = sdf0 - off;

                    self.sdf = Value::from_float(sdf);
                    self.inside = Value::from_float(-sdf);
                    self.execute(code, program);

                    self.pop_state();
                }
                NodeOp::DistanceBox(at, radius, rounding, offset, scale, code) => {
                    let at = if at.is_empty() {
                        self.point_at(Vec3::zero())
                    } else {
                        self.execute(at, program);
                        let p = self.stack.pop().unwrap().as_vec3();
                        self.point_at(p)
                    };

                    let size = if radius.is_empty() {
                        Vec3::broadcast(0.5)
                    } else {
                        self.execute(radius, program);
                        self.stack.pop().unwrap().as_vec3()
                    };

                    let rounding = if rounding.is_empty() {
                        0.0
                    } else {
                        self.execute(rounding, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.push_state();

                    let mut half = self.size_by_plane(size);
                    let s = self.eval_profile_scale(scale, program);
                    if s != 1.0 {
                        half *= Vec3::broadcast(s);
                    }

                    let sdf0 = self.sdf_box3d(self.local.as_vec3() - at, half, rounding);
                    let off = self.eval_profile_offset(offset, program);
                    let sdf = sdf0 - off;

                    self.sdf = Value::from_float(sdf);
                    self.inside = Value::from_float(-sdf);
                    self.execute(code, program);

                    self.pop_state();
                }
                NodeOp::DistanceCapsule(from, to, radius, offset, scale, code) => {
                    /// Signed distance to a capsule defined by segment a->b with radius r.
                    #[inline]
                    fn sdf_capsule(p: Vec3<f32>, a: Vec3<f32>, b: Vec3<f32>, r: f32) -> f32 {
                        let ba = b - a;
                        let baba = ba.dot(ba);
                        if baba <= 1e-8 {
                            return (p - a).magnitude() - r;
                        }
                        let pa = p - a;
                        let h = (pa.dot(ba) / baba).clamp(0.0, 1.0);
                        (pa - ba * h).magnitude() - r
                    }

                    let from: Vec3<f32> = if from.is_empty() {
                        self.point_at(Vec3::zero())
                    } else {
                        self.execute(from, program);
                        let p = self.stack.pop().unwrap().as_vec3();
                        self.point_at(p)
                    };

                    let to: Vec3<f32> = if to.is_empty() {
                        self.point_at(Vec3::zero())
                    } else {
                        self.execute(to, program);
                        let p = self.stack.pop().unwrap().as_vec3();
                        self.point_at(p)
                    };

                    let mut radius = if radius.is_empty() {
                        0.5
                    } else {
                        self.execute(radius, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.push_state();

                    let p = self.local.as_vec3();

                    let (_ub, _vb, u_raw_pre, v_raw_pre, d_along, len_axis) =
                        self.axial_frame_offsets(p, from, to, self.plane);
                    let t = if len_axis > 0.0 {
                        d_along / len_axis
                    } else {
                        0.0
                    };

                    let old_d = self.d;
                    self.d = Value::from_float(t);
                    let s = self.eval_profile_scale(scale, program);
                    self.d = old_d;
                    if s != 1.0 {
                        radius *= s;
                    }

                    let sdf0 = sdf_capsule(p, from, to, radius);

                    let u = (0.5 + u_raw_pre / (2.0 * radius.max(1e-9))).clamp(0.0, 1.0);
                    let v = (0.5 + v_raw_pre / (2.0 * radius.max(1e-9))).clamp(0.0, 1.0);
                    self.u = Value::from_float(u);
                    self.v = Value::from_float(v);
                    self.d = Value::from_float(t);

                    let off = self.eval_profile_offset(offset, program);
                    let sdf = sdf0 - off;

                    self.sdf = Value::from_float(sdf);
                    self.inside = Value::from_float(-sdf);
                    self.execute(code, program);

                    self.pop_state();
                }
                NodeOp::DistanceCylinder(from, to, radius, offset, scale, code) => {
                    #[inline]
                    fn sdf_capped_cylinder(
                        p: Vec3<f32>,
                        a: Vec3<f32>,
                        b: Vec3<f32>,
                        r: f32,
                    ) -> f32 {
                        let ba = b - a;
                        let pa = p - a;
                        let baba = ba.dot(ba);

                        if baba <= 1e-8 {
                            return pa.magnitude() - r;
                        }

                        let paba = pa.dot(ba);

                        let x = (pa * baba - ba * paba).magnitude() - r * baba;

                        let y = (paba - baba * 0.5).abs() - baba * 0.5;

                        let x2 = x * x;
                        let y2 = y * y * baba;

                        let d = if x.max(y) < 0.0 {
                            -(x2.min(y2))
                        } else {
                            (if x > 0.0 { x2 } else { 0.0 }) + (if y > 0.0 { y2 } else { 0.0 })
                        };

                        d.signum() * d.abs().sqrt() / baba
                    }

                    let from: Vec3<f32> = if from.is_empty() {
                        self.point_at(Vec3::zero())
                    } else {
                        self.execute(from, program);
                        let p = self.stack.pop().unwrap().as_vec3();
                        self.point_at(p)
                    };

                    let to: Vec3<f32> = if to.is_empty() {
                        self.point_at(Vec3::zero())
                    } else {
                        self.execute(to, program);
                        let p = self.stack.pop().unwrap().as_vec3();
                        self.point_at(p)
                    };

                    let mut r = if radius.is_empty() {
                        0.5
                    } else {
                        self.execute(radius, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.push_state();
                    let p = self.local.as_vec3();

                    let (_ub, _vb, u_raw_pre, v_raw_pre, d_along, len_axis) =
                        self.axial_frame_offsets(p, from, to, self.plane);
                    let t = if len_axis > 0.0 {
                        d_along / len_axis
                    } else {
                        0.0
                    };

                    let old_d = self.d;
                    self.d = Value::from_float(t);
                    let s = self.eval_profile_scale(scale, program);
                    self.d = old_d;
                    if s != 1.0 {
                        r *= s;
                    }

                    let sdf0 = sdf_capped_cylinder(p, from, to, r);

                    let u = (0.5 + u_raw_pre / (2.0 * r.max(1e-9))).clamp(0.0, 1.0);
                    let v = (0.5 + v_raw_pre / (2.0 * r.max(1e-9))).clamp(0.0, 1.0);
                    self.u = Value::from_float(u);
                    self.v = Value::from_float(v);
                    self.d = Value::from_float(t);

                    let off = self.eval_profile_offset(offset, program);
                    let sdf = sdf0 - off;

                    self.sdf = Value::from_float(sdf);
                    self.inside = Value::from_float(-sdf);
                    self.execute(code, program);
                    self.pop_state();
                }
                NodeOp::DistanceCone(from, to, radius1, radius2, offset, scale, code) => {
                    #[inline]
                    fn sdf_capped_cone(
                        p: Vec3<f32>,
                        a: Vec3<f32>,
                        b: Vec3<f32>,
                        ra: f32,
                        rb: f32,
                    ) -> f32 {
                        let ba = b - a;
                        let pa = p - a;
                        let rba = rb - ra;
                        let baba = ba.dot(ba);

                        // Degenerate axis → treat as sphere at `a` with radius min(ra, rb)
                        if baba <= 1e-8 {
                            return pa.magnitude() - ra.min(rb);
                        }

                        let papa = pa.dot(pa);
                        let paba = pa.dot(ba) / baba;

                        // x = sqrt( papa - paba*paba*baba )
                        let x2 = (papa - paba * paba * baba).max(0.0);
                        let x = x2.sqrt();

                        // cax = max(0, x - (paba < 0.5 ? ra : rb))
                        let cax = (x - if paba < 0.5 { ra } else { rb }).max(0.0);

                        // cay = abs(paba - 0.5) - 0.5
                        let cay = (paba - 0.5).abs() - 0.5;

                        let k = rba * rba + baba;

                        // f = clamp( (rba*(x - ra) + paba*baba)/k, 0, 1 )
                        let f = ((rba * (x - ra) + paba * baba) / k).clamp(0.0, 1.0);

                        // cbx = x - ra - f*rba
                        // cby = paba - f
                        let cbx = x - ra - f * rba;
                        let cby = paba - f;

                        // s = (cbx < 0 && cay < 0) ? -1 : 1
                        let s = if cbx < 0.0 && cay < 0.0 { -1.0 } else { 1.0 };

                        // return s * sqrt( min(cax^2 + cay^2*baba, cbx^2 + cby^2*baba) )
                        let d1 = cax * cax + cay * cay * baba;
                        let d2 = cbx * cbx + cby * cby * baba;

                        s * d1.min(d2).sqrt()
                    }

                    let a: Vec3<f32> = if from.is_empty() {
                        self.point_at(Vec3::zero())
                    } else {
                        self.execute(from, program);
                        let p = self.stack.pop().unwrap().as_vec3();
                        self.point_at(p)
                    };

                    let b: Vec3<f32> = if to.is_empty() {
                        self.point_at(Vec3::zero())
                    } else {
                        self.execute(to, program);
                        let p = self.stack.pop().unwrap().as_vec3();
                        self.point_at(p)
                    };

                    let mut r1 = if radius1.is_empty() {
                        0.5
                    } else {
                        self.execute(radius1, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    let mut r2 = if radius2.is_empty() {
                        0.25
                    } else {
                        self.execute(radius2, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.push_state();
                    let p = self.local.as_vec3();

                    let (_ub, _vb, u_raw_pre, v_raw_pre, d_along, len_axis) =
                        self.axial_frame_offsets(p, a, b, self.plane);
                    let t = if len_axis > 0.0 {
                        d_along / len_axis
                    } else {
                        0.0
                    };

                    let old_d = self.d;
                    self.d = Value::from_float(t);
                    let s = self.eval_profile_scale(scale, program);
                    self.d = old_d;
                    if s != 1.0 {
                        r1 *= s;
                        r2 *= s;
                    }

                    let sdf0 = sdf_capped_cone(p, a, b, r1, r2);

                    let r_loc = r1 + (r2 - r1) * t;
                    let u = (0.5 + u_raw_pre / (2.0 * r_loc.max(1e-9))).clamp(0.0, 1.0);
                    let v = (0.5 + v_raw_pre / (2.0 * r_loc.max(1e-9))).clamp(0.0, 1.0);
                    self.u = Value::from_float(u);
                    self.v = Value::from_float(v);
                    self.d = Value::from_float(t);

                    let off = self.eval_profile_offset(offset, program);
                    let sdf = sdf0 - off;

                    self.sdf = Value::from_float(sdf);
                    self.inside = Value::from_float(-sdf);
                    self.execute(code, program);
                    self.pop_state();
                }
                NodeOp::DistanceVesica(from, to, radius, offset, scale, code) => {
                    #[inline]
                    fn sdf_vesica_segment(p: Vec3<f32>, a: Vec3<f32>, b: Vec3<f32>, w: f32) -> f32 {
                        // Center and axis
                        let c = (a + b) * 0.5;
                        let ba = b - a;
                        let l = ba.magnitude();

                        // Guard against degenerate segment
                        if l <= 1e-6 {
                            // When a≈b, this reduces to a circle/sphere-like case.
                            // Treat as a sphere of radius w around the midpoint.
                            return (p - c).magnitude() - w;
                        }

                        let v = ba / l; // axis unit vector
                        let pc = p - c;
                        let y = pc.dot(v); // axial coordinate
                        let x_r = (pc - v * y).magnitude(); // radial distance to axis (in XZ plane of the local frame)
                        let q = Vec2::new(x_r, y.abs());

                        let r = 0.5 * l; // circle radius used by the construction
                                         // 'w' is the lens half-thickness (aperture), not a radius
                        let d = 0.5 * (r * r - w * w) / w;

                        // Region selection: cap vs side
                        let h = if r * q.x < d * (q.y - r) {
                            // cap region
                            Vec3::new(0.0, r, 0.0)
                        } else {
                            // side region
                            Vec3::new(-d, 0.0, d + w)
                        };

                        let hxy = Vec2::new(h.x, h.y);
                        (q - hxy).magnitude() - h.z
                    }
                    let from: Vec3<f32> = if from.is_empty() {
                        self.point_at(Vec3::zero())
                    } else {
                        self.execute(from, program);
                        let p = self.stack.pop().unwrap().as_vec3();
                        self.point_at(p)
                    };

                    let to: Vec3<f32> = if to.is_empty() {
                        self.point_at(Vec3::zero())
                    } else {
                        self.execute(to, program);
                        let p = self.stack.pop().unwrap().as_vec3();
                        self.point_at(p)
                    };

                    let mut w = if radius.is_empty() {
                        0.5
                    } else {
                        self.execute(radius, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.push_state();
                    let p = self.local.as_vec3();

                    let (_ub, _vb, u_raw_pre, v_raw_pre, d_along, len_axis) =
                        self.axial_frame_offsets(p, from, to, self.plane);
                    let t = if len_axis > 0.0 {
                        d_along / len_axis
                    } else {
                        0.0
                    };

                    let old_d = self.d;
                    self.d = Value::from_float(t);
                    let s = self.eval_profile_scale(scale, program);
                    self.d = old_d;
                    if s != 1.0 {
                        w *= s;
                    }

                    let sdf0 = sdf_vesica_segment(p, from, to, w);

                    let u = (0.5 + u_raw_pre / (2.0 * w.max(1e-9))).clamp(0.0, 1.0);
                    let v = (0.5 + v_raw_pre / (2.0 * w.max(1e-9))).clamp(0.0, 1.0);
                    self.u = Value::from_float(u);
                    self.v = Value::from_float(v);
                    self.d = Value::from_float(t);

                    let off = self.eval_profile_offset(offset, program);
                    let sdf = sdf0 - off;

                    self.sdf = Value::from_float(sdf);
                    self.inside = Value::from_float(-sdf);
                    self.execute(code, program);
                    self.pop_state();
                }
                NodeOp::DistanceNgonFrustum(
                    from,
                    to,
                    sides,
                    base,
                    top,
                    phase,
                    offset,
                    scale,
                    code,
                ) => {
                    #[inline]
                    fn sdf_ngon_frustum_between(
                        p: Vec3<f32>,
                        a: Vec3<f32>,
                        b: Vec3<f32>,
                        ra: f32,
                        rb: f32,
                        sides: i32,
                        phase: f32,
                    ) -> f32 {
                        let ba = b - a;
                        let len2 = ba.dot(ba);
                        if len2 <= 1e-8 {
                            // Degenerate: sphere at `a` with radius min(ra, rb)
                            return (p - a).magnitude() - ra.min(rb);
                        }

                        let len = len2.sqrt();
                        let dir = ba / len;

                        // Orthonormal frame (right, up, dir)
                        let tmp_up = if dir.z.abs() < 0.99 {
                            Vec3::new(0.0, 0.0, 1.0)
                        } else {
                            Vec3::new(0.0, 1.0, 0.0)
                        };
                        let right = dir.cross(tmp_up).normalized();
                        let up = right.cross(dir).normalized();

                        // Local coords with origin at midpoint; y = along axis
                        let mid = (a + b) * 0.5;
                        let rel = p - mid;
                        let x = rel.dot(right);
                        let y = rel.dot(dir);
                        let z = rel.dot(up);

                        // Half-height and linear half-size s(y) = s0 + k*y
                        let h = 0.5 * len;
                        let s0 = 0.5 * (ra + rb);
                        let k = if h > 0.0 { (rb - ra) / (2.0 * h) } else { 0.0 };
                        let nscale = (1.0 + k * k).sqrt(); // |(t, -k)|

                        // Caps
                        let dtop = y - h;
                        let dbot = -y - h;

                        // Side planes (regular N-gon)
                        let n = sides.max(3);
                        let mut dside = f32::NEG_INFINITY;
                        let tau = std::f32::consts::TAU;
                        for i in 0..n {
                            let ang = phase + tau * (i as f32) / (n as f32);
                            let c = ang.cos();
                            let s = ang.sin();
                            let x_n = x * c + z * s; // project onto side direction
                            let d_plane = (x_n - k * y - s0) / nscale;
                            if d_plane > dside {
                                dside = d_plane;
                            }
                        }

                        // Intersection of half-spaces (exact for convex polyhedron)
                        dside.max(dtop).max(dbot)
                    }
                    let a: Vec3<f32> = if from.is_empty() {
                        self.point_at(Vec3::zero())
                    } else {
                        self.execute(from, program);
                        let uvw = self.stack.pop().unwrap().as_vec3();
                        self.point_at(uvw)
                    };

                    let b: Vec3<f32> = if to.is_empty() {
                        self.point_at(Vec3::new(0.0, 0.0, 1.0))
                    } else {
                        self.execute(to, program);
                        let uvw = self.stack.pop().unwrap().as_vec3();
                        self.point_at(uvw)
                    };

                    let n_sides: i32 = if sides.is_empty() {
                        4
                    } else {
                        self.execute(sides, program);
                        (self.stack.pop().unwrap().as_float() as i32).max(3)
                    };

                    let mut ra = if base.is_empty() {
                        0.5
                    } else {
                        self.execute(base, program);
                        self.stack.pop().unwrap().as_float()
                    };
                    let mut rb = if top.is_empty() {
                        0.0
                    } else {
                        self.execute(top, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    let phase_val = if phase.is_empty() {
                        0.0
                    } else {
                        self.execute(phase, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.push_state();
                    let p = self.local.as_vec3();

                    let (_ub, _vb, u_raw_pre, v_raw_pre, d_along, len_axis) =
                        self.axial_frame_offsets(p, a, b, self.plane);
                    let t = if len_axis > 0.0 {
                        d_along / len_axis
                    } else {
                        0.0
                    };

                    let old_d = self.d;
                    self.d = Value::from_float(t);
                    let s = self.eval_profile_scale(scale, program);
                    self.d = old_d;
                    if s != 1.0 {
                        ra *= s;
                        rb *= s;
                    }

                    let sdf0 = sdf_ngon_frustum_between(p, a, b, ra, rb, n_sides, phase_val);

                    let s_loc = ra + (rb - ra) * t;
                    let u = (0.5 + u_raw_pre / (2.0 * s_loc.max(1e-9))).clamp(0.0, 1.0);
                    let v = (0.5 + v_raw_pre / (2.0 * s_loc.max(1e-9))).clamp(0.0, 1.0);
                    self.u = Value::from_float(u);
                    self.v = Value::from_float(v);
                    self.d = Value::from_float(t);

                    let off = self.eval_profile_offset(offset, program);
                    let sdf = sdf0 - off;

                    self.sdf = Value::from_float(sdf);
                    self.inside = Value::from_float(-sdf);
                    self.execute(code, program);
                    self.pop_state();
                }
                NodeOp::DistanceRectFrustum(
                    from,
                    to,
                    base_wh,
                    top_wh,
                    angle,
                    offset,
                    scale,
                    code,
                ) => {
                    /// Signed distance to a rectangular frustum between `a` and `b`.
                    #[inline]
                    fn sdf_rect_frustum_between(
                        p: Vec3<f32>,
                        a: Vec3<f32>,
                        b: Vec3<f32>,
                        ra: Vec2<f32>,
                        rb: Vec2<f32>,
                        angle_rad: f32,
                    ) -> f32 {
                        let ba = b - a;
                        let len2 = ba.dot(ba);
                        if len2 <= 1e-8 {
                            // Degenerate: thin box at `a` using average half-sizes
                            let half = Vec3::new((ra.x + rb.x) * 0.5, 1e-6, (ra.y + rb.y) * 0.5);
                            let q = (p - a).map(|v| v.abs()) - half;
                            return q.map(|v| v.max(0.0)).magnitude()
                                + q.x.max(q.y.max(q.z)).min(0.0);
                        }

                        let len = len2.sqrt();
                        let dir = ba / len;

                        // Orthonormal frame (right, up, dir)
                        let tmp_up = if dir.z.abs() < 0.99 {
                            Vec3::new(0.0, 0.0, 1.0)
                        } else {
                            Vec3::new(0.0, 1.0, 0.0)
                        };
                        let right = dir.cross(tmp_up).normalized();
                        let up = right.cross(dir).normalized();

                        // Local coords (origin at midpoint), y along axis
                        let mid = (a + b) * 0.5;
                        let rel = p - mid;
                        let mut x = rel.dot(right);
                        let y = rel.dot(dir);
                        let mut z = rel.dot(up);

                        // Rotate cross-section by angle (radians)
                        let (s, c) = angle_rad.sin_cos();
                        let xr = x * c - z * s;
                        let zr = x * s + z * c;
                        x = xr;
                        z = zr;

                        // Half-height and linear half-sizes:
                        // sx(y) = s0x + kx*y,  sz(y) = s0z + kz*y
                        let h = 0.5 * len;
                        let s0x = 0.5 * (ra.x + rb.x);
                        let s0z = 0.5 * (ra.y + rb.y);
                        let kx = if h > 0.0 {
                            (rb.x - ra.x) / (2.0 * h)
                        } else {
                            0.0
                        };
                        let kz = if h > 0.0 {
                            (rb.y - ra.y) / (2.0 * h)
                        } else {
                            0.0
                        };
                        let nx = (1.0 + kx * kx).sqrt();
                        let nz = (1.0 + kz * kz).sqrt();

                        // Four side planes (exact) and two caps
                        let dxp = (x - kx * y - s0x) / nx;
                        let dxn = (-x - kx * y - s0x) / nx;
                        let dzp = (z - kz * y - s0z) / nz;
                        let dzn = (-z - kz * y - s0z) / nz;

                        let dtop = y - h;
                        let dbot = -y - h;

                        dxp.max(dxn).max(dzp).max(dzn).max(dtop).max(dbot)
                    }
                    let a: Vec3<f32> = if from.is_empty() {
                        self.point_at(Vec3::zero())
                    } else {
                        self.execute(from, program);
                        let p = self.stack.pop().unwrap().as_vec3();
                        self.point_at(p)
                    };

                    let b: Vec3<f32> = if to.is_empty() {
                        self.point_at(Vec3::new(0.0, 0.0, 1.0))
                    } else {
                        self.execute(to, program);
                        let p = self.stack.pop().unwrap().as_vec3();
                        self.point_at(p)
                    };

                    let base_wh_val: Vec2<f32> = if base_wh.is_empty() {
                        Vec2::new(1.0, 1.0)
                    } else {
                        self.execute(base_wh, program);
                        self.stack.pop().unwrap().as_vec2()
                    };

                    let top_wh_val: Vec2<f32> = if top_wh.is_empty() {
                        base_wh_val
                    } else {
                        self.execute(top_wh, program);
                        self.stack.pop().unwrap().as_vec2()
                    };

                    let angle_rad: f32 = if angle.is_empty() {
                        0.0
                    } else {
                        self.execute(angle, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    // Convert to half-sizes for SDF
                    let mut ra = base_wh_val * 0.5;
                    let mut rb = top_wh_val * 0.5;

                    self.push_state();

                    let p = self.local.as_vec3();

                    let (_ub, _vb, u_raw_pre, v_raw_pre, d_along, len_axis) =
                        self.axial_frame_offsets(p, a, b, self.plane);
                    let t = if len_axis > 0.0 {
                        d_along / len_axis
                    } else {
                        0.0
                    };

                    let old_d = self.d;
                    self.d = Value::from_float(t);
                    let s = self.eval_profile_scale(scale, program);
                    self.d = old_d;

                    if s != 1.0 {
                        ra *= s;
                        rb *= s;
                    }

                    let sdf0 = sdf_rect_frustum_between(p, a, b, ra, rb, angle_rad);

                    let hx = ra.x + (rb.x - ra.x) * t;
                    let hz = ra.y + (rb.y - ra.y) * t;
                    let u = (0.5 + u_raw_pre / (2.0 * hx.max(1e-9))).clamp(0.0, 1.0);
                    let v = (0.5 + v_raw_pre / (2.0 * hz.max(1e-9))).clamp(0.0, 1.0);

                    self.u = Value::from_float(u);
                    self.v = Value::from_float(v);
                    self.d = Value::from_float(t);

                    let off = self.eval_profile_offset(offset, program);
                    let sdf = sdf0 - off;

                    self.sdf = Value::from_float(sdf);
                    self.inside = Value::from_float(-sdf);

                    self.execute(code, program);
                    self.pop_state();
                }
                NodeOp::Volume(code) => {
                    if self.inside.as_float() >= 0.0 {
                        self.execute(code, program);
                    }
                }
                // Material Write Instructions
                NodeOp::MaterialAlbedo => {
                    if let Some(top) = self.stack.last() {
                        self.material.base_color = top.as_vec3();
                    }
                }
                NodeOp::MaterialSubsurface => {
                    if let Some(top) = self.stack.last() {
                        self.material.subsurface = top.as_float();
                    }
                }
                NodeOp::MaterialMetallic => {
                    if let Some(top) = self.stack.last() {
                        self.material.metallic = top.as_float();
                    }
                }
                NodeOp::MaterialSpecularTint => {
                    if let Some(top) = self.stack.last() {
                        self.material.specular_tint = top.as_float();
                    }
                }
                NodeOp::MaterialRoughness => {
                    if let Some(top) = self.stack.last() {
                        self.material.roughness = top.as_float();
                    }
                }
                NodeOp::MaterialAnisotropic => {
                    if let Some(top) = self.stack.last() {
                        self.material.anisotropic = top.as_float();
                    }
                }
                NodeOp::MaterialSheen => {
                    if let Some(top) = self.stack.last() {
                        self.material.sheen = top.as_float();
                    }
                }
                NodeOp::MaterialSheenTint => {
                    if let Some(top) = self.stack.last() {
                        self.material.sheen_tint = top.as_float();
                    }
                }
                NodeOp::MaterialClearcoat => {
                    if let Some(top) = self.stack.last() {
                        self.material.clearcoat = top.as_float();
                    }
                }
                NodeOp::MaterialClearcoatGloss => {
                    if let Some(top) = self.stack.last() {
                        self.material.clearcoat_roughness = top.as_float();
                    }
                }
                NodeOp::MaterialIOR => {
                    if let Some(top) = self.stack.last() {
                        self.material.ior = top.as_float();
                    }
                }
                NodeOp::MaterialTransmission => {
                    if let Some(top) = self.stack.last() {
                        self.material.spec_trans = top.as_float();
                    }
                }
                NodeOp::MaterialEmission => {
                    if let Some(top) = self.stack.last() {
                        self.material.emission = top.as_vec3();
                    }
                }
                NodeOp::MediumAbsorb => {
                    self.material.medium.role = MediumRole::Absorb;
                }
                NodeOp::MediumScatter => {
                    self.material.medium.role = MediumRole::Scatter;
                }
                NodeOp::MediumEmissive => {
                    self.material.medium.role = MediumRole::Emissive;
                }
                NodeOp::MediumDensity => {
                    if let Some(top) = self.stack.last() {
                        self.material.medium.density = top.as_float();
                    }
                }
                NodeOp::MediumAnisotropy => {
                    if let Some(top) = self.stack.last() {
                        self.material.medium.anisotropy = top.as_float();
                    }
                }
                NodeOp::MediumColor => {
                    if let Some(top) = self.stack.last() {
                        self.material.medium.color = top.as_vec3();
                        self.material.base_color = top.as_vec3();
                    }
                }
            }
        }
    }

    /// Place a voxel box into the world. We first model into a separate grid
    /// and than merge back into the program grid.
    pub fn place(&mut self, id: &String, at: Vec3<f32>, program: &mut Program) {
        let voxel = match program.voxels.get(id) {
            Some(defined) => defined.clone(),
            None => return,
        };

        let mut grid = VoxelGrid::empty(program.grid.read().unwrap().density);

        let mut execution = Execution::new_from_var(&self);
        let mut size = Vec3::new(1.0, 1.0, 1.0);
        execution.execute(&voxel.size, program);
        if let Some(value) = execution.stack.last() {
            size = value.as_vec3();
        }

        let rect = VoxelRect {
            origin: at - size * 0.5,
            size,
        };

        let voxel_size = 1.0 / grid.density_f;

        let tile_min = (
            rect.origin.x.floor() as i32,
            rect.origin.y.floor() as i32,
            rect.origin.z.floor() as i32,
        );
        let tile_max = (
            (rect.origin.x + rect.size.x).ceil() as i32 - 1,
            (rect.origin.y + rect.size.y).ceil() as i32 - 1,
            (rect.origin.z + rect.size.z).ceil() as i32 - 1,
        );

        let tile_keys: Vec<Coord> = (tile_min.2..=tile_max.2)
            .flat_map(|tz| {
                (tile_min.1..=tile_max.1)
                    .flat_map(move |ty| (tile_min.0..=tile_max.0).map(move |tx| (tx, ty, tz)))
            })
            .collect();

        let aabb = Aabb {
            min: -size * 0.5,
            max: size * 0.5,
        };

        let produced: Vec<(Coord, Tile)> = tile_keys
            .into_par_iter()
            .map(|tile_key| {
                let mut tile = Tile::new(grid.density);
                let tile_origin = Vec3::new(tile_key.0 as F, tile_key.1 as F, tile_key.2 as F);

                let mut exec = Execution::new_from_var(self);
                let mut p = Program::new(Vec3::zero(), grid.density);

                for z in 0..grid.density {
                    for y in 0..grid.density {
                        for x in 0..grid.density {
                            let world = (tile_origin
                                + Vec3::new(x as F, y as F, z as F) / grid.density_f)
                                + Vec3::broadcast(voxel_size * 0.5);

                            // let world = world_abs - center;
                            let local = world - at;

                            exec.stack.clear();
                            exec.world = Value::from_vec3(world);
                            exec.local = Value::from_vec3(local);
                            exec.bbox = aabb;

                            exec.execute(&voxel.body, &mut p);
                            if let Some(val) = exec.stack.last() {
                                let mat = val.x();
                                if mat >= 0.0 {
                                    let hash = (exec.hash * 255.0).floor() as u8;
                                    tile.set(
                                        (x as i32, y as i32, z as i32),
                                        Voxel::new(mat as u8, hash),
                                    );
                                }
                            }
                        }
                    }
                }

                let grid_offset = (rect.origin + rect.size * 0.5).map(|v| v.floor() as i32);
                let tile_key_offset = (
                    tile_key.0 + grid_offset.x,
                    tile_key.1 + grid_offset.y,
                    tile_key.2 + grid_offset.z,
                );

                (tile_key_offset, tile)
            })
            .collect();

        for (key, tile) in produced {
            grid.tiles.insert(key, tile);
        }

        program.grid.write().unwrap().merge(&grid);
    }

    /// SDF to a Hexagon
    #[inline]
    fn _sdf_hex(p: Vec2<f32>, radius: f32) -> f32 {
        let k = Vec2::new(-0.8660254, 0.5); // cos(π/6), sin(π/6)
        let p = p.map(|v| v.abs());

        let a = p - k * (p.dot(k)).min(radius);
        let b = p - Vec2::new(radius, 0.0);
        let inside = if p.y > radius * 0.5 { a } else { b };

        inside.magnitude() * inside.y.signum()
    }

    /// SDF to a 2D box
    #[inline]
    fn sdf_box(&self, p: Vec2<f32>, b: Vec2<f32>, r: f32) -> f32 {
        let d = p.map(|v| v.abs()) - b + Vec2::broadcast(r);
        d.x.max(d.y).min(0.0) + (d.map(|v| v.max(0.0))).magnitude() - r
    }

    /// SDF to a 3D box
    #[inline]
    fn sdf_box3d(&self, p: Vec3<f32>, b: Vec3<f32>, r: f32) -> f32 {
        let d = p.map(|v| v.abs()) - b + Vec3::broadcast(r);
        d.x.max(d.y).max(d.z).min(0.0) + d.map(|v| v.max(0.0)).magnitude() - r
    }

    /// Reshuffles the size components based on the current plane.
    fn size_by_plane(&self, size: Vec3<f32>) -> Vec3<f32> {
        match self.plane {
            Plane::XY => Vec3::new(size.x, size.y, size.z),
            Plane::XZ => Vec3::new(size.x, size.z, size.y),
            Plane::YZ => Vec3::new(size.y, size.z, size.x),
            Plane::ZY => Vec3::new(size.z, size.y, size.x),
        }
    }

    /// Hash21
    #[inline]
    fn hash21(&self, p: Vec2<f32>) -> f32 {
        let dot = p.x * 127.1 + p.y * 311.7;
        (dot.sin().fract() * 43758.5453).fract()
    }

    #[inline]
    fn smooth_min(&self, a: f32, b: f32, k: f32) -> f32 {
        let h = (0.5 + 0.5 * (b - a) / k).clamp(0.0, 1.0);
        let m = b * (1.0 - h) + a * h;
        m - k * h * (1.0 - h)
    }

    /// Define a point relative to the current segment and shape
    fn point_at(&self, uvw: Vec3<f32>) -> Vec3<f32> {
        let size = self.bbox.size();
        let offset = self.bbox.min;

        match self.plane {
            Plane::XY => Vec3::new(
                offset.x + uvw.x * size.w,
                offset.y + uvw.y * size.h,
                offset.z + uvw.z * size.d,
            ),
            Plane::XZ => Vec3::new(
                offset.x + uvw.x * size.w,
                offset.y + uvw.z * size.h,
                offset.z + uvw.y * size.d,
            ),
            Plane::YZ => Vec3::new(
                offset.x + uvw.z * size.w,
                offset.y + uvw.x * size.h,
                offset.z + uvw.y * size.d,
            ),
            Plane::ZY => Vec3::new(
                offset.x + uvw.z * size.w,
                offset.y + uvw.y * size.h,
                offset.z + uvw.x * size.d,
            ),
        }
    }

    /// Build a plane-aligned perpendicular frame to axis a->b and return
    /// (u_basis, v_basis, u_raw, v_raw, d_along, len).
    /// - u_raw, v_raw are the perpendicular components in that frame (local units)
    /// - d_along is clamped to [0..len] in local units
    #[inline]
    fn axial_frame_offsets(
        &self,
        p: Vec3<f32>,
        a: Vec3<f32>,
        b: Vec3<f32>,
        plane: Plane,
    ) -> (Vec3<f32>, Vec3<f32>, f32, f32, f32, f32) {
        let ba = b - a;
        let len = ba.magnitude();
        if len <= 1e-6 {
            // Degenerate: use plane axes at `a`
            let axis_u = match plane {
                Plane::XY => Vec3::new(1.0, 0.0, 0.0),
                Plane::XZ => Vec3::new(1.0, 0.0, 0.0),
                Plane::YZ => Vec3::new(0.0, 1.0, 0.0),
                Plane::ZY => Vec3::new(0.0, 0.0, 1.0),
            };
            let axis_v = match plane {
                Plane::XY => Vec3::new(0.0, 1.0, 0.0),
                Plane::XZ => Vec3::new(0.0, 0.0, 1.0),
                Plane::YZ => Vec3::new(0.0, 0.0, 1.0),
                Plane::ZY => Vec3::new(0.0, 1.0, 0.0),
            };
            let offset = p - a;
            let u_raw = offset.dot(axis_u);
            let v_raw = offset.dot(axis_v);
            return (axis_u, axis_v, u_raw, v_raw, 0.0, 0.0);
        }

        let dir = ba / len;
        let pa = p - a;
        let d_along = pa.dot(dir).clamp(0.0, len);
        let offset = pa - dir * d_along; // perpendicular to axis

        // Preferred plane-aligned directions
        let axis_u = match plane {
            Plane::XY => Vec3::new(1.0, 0.0, 0.0),
            Plane::XZ => Vec3::new(1.0, 0.0, 0.0),
            Plane::YZ => Vec3::new(0.0, 1.0, 0.0),
            Plane::ZY => Vec3::new(0.0, 0.0, 1.0),
        };
        let axis_v = match plane {
            Plane::XY => Vec3::new(0.0, 1.0, 0.0),
            Plane::XZ => Vec3::new(0.0, 0.0, 1.0),
            Plane::YZ => Vec3::new(0.0, 0.0, 1.0),
            Plane::ZY => Vec3::new(0.0, 1.0, 0.0),
        };

        // Project plane axes onto the plane perpendicular to `dir`
        let mut u_basis = axis_u - dir * axis_u.dot(dir);
        let mut u_len = u_basis.magnitude();
        if u_len < 1e-6 {
            u_basis = axis_v - dir * axis_v.dot(dir);
            u_len = u_basis.magnitude();
        }
        if u_len < 1e-6 {
            let tmp = if dir.z.abs() < 0.99 {
                Vec3::new(0.0, 0.0, 1.0)
            } else {
                Vec3::new(0.0, 1.0, 0.0)
            };
            u_basis = dir.cross(tmp);
            u_len = u_basis.magnitude();
        }
        u_basis = u_basis / u_len;

        let mut v_basis = axis_v - dir * axis_v.dot(dir);
        v_basis = v_basis - u_basis * v_basis.dot(u_basis);
        let mut v_len = v_basis.magnitude();
        if v_len < 1e-6 {
            v_basis = dir.cross(u_basis);
            v_len = v_basis.magnitude();
        }
        v_basis = v_basis / v_len;

        // Align signs to match plane axes
        if u_basis.dot(axis_u) < 0.0 {
            u_basis = -u_basis;
        }
        if v_basis.dot(axis_v) < 0.0 {
            v_basis = -v_basis;
        }

        let u_raw = offset.dot(u_basis);
        let v_raw = offset.dot(v_basis);
        (u_basis, v_basis, u_raw, v_raw, d_along, len)
    }

    // White noise, the hash is not good enough, should be replaced.
    #[inline]
    fn white_noise(&self) -> f32 {
        let p = self.local.as_vec3();

        let dot = (p.x + p.z) * 127.1 + (p.y + p.z) * 311.7 + (p.x + p.y) * 74.7;
        (dot.sin() * 43758.5453).fract()
    }

    /// Value noise 3D
    /// Base on https://www.shadertoy.com/view/4dS3Wd
    fn value_noise(&self, octaves: i32, scale: Vec3<f32>) -> f32 {
        fn hash(mut p: f32) -> f32 {
            p = (p * 0.011).fract();
            p *= p + 7.5;
            p *= p + p;
            p.fract()
        }

        fn noise(x: Vec3<f32>) -> f32 {
            let step = Vec3::new(110.0, 241.0, 171.0);

            let i = x.map(|v| v.floor());
            let f = x.map(|v| v.fract());

            let n = i.dot(step);

            let u = f * f * f.map(|v| 3.0 - 2.0 * v);

            lerp(
                lerp(
                    lerp(
                        hash(n + step.dot(Vec3::new(0.0, 0.0, 0.0))),
                        hash(n + step.dot(Vec3::new(1.0, 0.0, 0.0))),
                        u.x,
                    ),
                    lerp(
                        hash(n + step.dot(Vec3::new(0.0, 1.0, 0.0))),
                        hash(n + step.dot(Vec3::new(1.0, 1.0, 0.0))),
                        u.x,
                    ),
                    u.y,
                ),
                lerp(
                    lerp(
                        hash(n + step.dot(Vec3::new(0.0, 0.0, 1.0))),
                        hash(n + step.dot(Vec3::new(1.0, 0.0, 1.0))),
                        u.x,
                    ),
                    lerp(
                        hash(n + step.dot(Vec3::new(0.0, 1.0, 1.0))),
                        hash(n + step.dot(Vec3::new(1.0, 1.0, 1.0))),
                        u.x,
                    ),
                    u.y,
                ),
                u.z,
            )
        }

        let p = self.local.as_vec3();

        let mut x = Vec3::new(1240.0, 1240.0, 1240.0) + p * 8.0 * scale;

        if octaves == 0 {
            return noise(x);
        }

        let mut v = 0.0;
        let mut a = 0.5;
        let shift = Vec3::new(100.0, 100.0, 100.0);
        for _ in 0..octaves {
            v += a * noise(x);
            x = x * 2.0 + shift;
            a *= 0.5;
        }
        v
    }

    /// Profile offset evaluation
    #[inline]
    fn eval_profile_offset(&mut self, body: &Vec<NodeOp>, program: &mut Program) -> f32 {
        if !body.is_empty() {
            let sp = self.stack.len();
            self.execute(body, program);
            let mut out = 0.0;
            while self.stack.len() > sp {
                out = self.stack.pop().unwrap().as_float();
            }
            out
        } else {
            0.0
        }
    }

    /// Profile scale evaluation
    #[inline]
    fn eval_profile_scale(&mut self, body: &Vec<NodeOp>, program: &mut Program) -> f32 {
        if !body.is_empty() {
            let sp = self.stack.len();
            self.execute(body, program);
            let mut out = 0.0;
            while self.stack.len() > sp {
                out = self.stack.pop().unwrap().as_float();
            }
            if out.is_finite() {
                out.max(0.0)
            } else {
                1.0
            }
        } else {
            1.0
        }
    }

    // Push the current segmentation state.
    fn push_state(&mut self) {
        self.state_stack.push(SegmentationState {
            bbox: self.bbox.clone(),
            plane: self.plane,
            u: self.u,
            v: self.v,
            d: self.d,
            sdf: self.sdf,
            inside: self.inside,
        });
    }

    // Pop the last segmentation state.
    fn pop_state(&mut self) {
        if let Some(state) = self.state_stack.pop() {
            self.bbox = state.bbox;
            self.plane = state.plane;
            self.u = state.u;
            self.v = state.v;
            self.d = state.d;
            self.sdf = state.sdf;
            self.inside = state.inside;
        }
    }

    // Push the current locals state when we enter a function.
    fn push_locals_state(&mut self) {
        self.locals_stack.push(self.locals.clone());
    }

    // Pop the last locals state when we exit a function.
    fn pop_locals_state(&mut self) {
        if let Some(state) = self.locals_stack.pop() {
            self.locals = state;
        }
    }
}
