use crate::prelude::*;
use rayon::prelude::*;

#[derive(Clone)]
pub struct SegmentationState {
    pub bbox: Aabb<f32>,
    pub plane: Plane,
    pub u: Value,
    pub v: Value,
    pub d: Value,
    pub sdf: Value,
    pub inside: Value,
}

#[derive(Clone)]
pub struct Execution {
    pub variables: Vec<Value>,

    /// The world coordinate of the current voxel
    pub world: Value,
    /// The segment transformed local coordinate
    pub local: Value,
    /// The segment computed u value
    pub u: Value,
    /// The segment computed v value
    pub v: Value,
    /// The segment computed d (depth) value
    pub d: Value,
    /// The current plane
    pub plane: Plane,
    /// The shape computed distance value
    pub sdf: Value,
    /// -sdf
    pub inside: Value,

    /// The current segmentation state
    state_stack: Vec<SegmentationState>,

    /// Hash, generated by patterns and passed on to the materials.
    pub hash: f32,

    /// The current bbox of the model space. Gets subdivided by segments during
    /// execution.
    pub bbox: Aabb<f32>,

    /// The material the VM writes to.
    pub material: BSDFMaterial,

    /// The execution stack.
    pub stack: Vec<Value>,
}

impl Execution {
    pub fn new(var_size: usize) -> Self {
        Self {
            variables: vec![Value::zero(); var_size],
            world: Value::zero(),
            local: Value::zero(),
            u: Value::zero(),
            v: Value::zero(),
            d: Value::zero(),
            plane: Plane::XZ,
            sdf: Value::zero(),
            inside: Value::zero(),
            state_stack: Vec::with_capacity(8),
            hash: 1.0,
            bbox: Aabb {
                min: Vec3::zero(),
                max: Vec3::one(),
            },
            material: BSDFMaterial::default(),
            stack: Vec::with_capacity(32),
        }
    }

    pub fn new_from_var(execution: &Execution) -> Self {
        Self {
            variables: execution.variables.clone(),
            world: Value::zero(),
            local: Value::zero(),
            u: Value::zero(),
            v: Value::zero(),
            d: Value::zero(),
            plane: Plane::XZ,
            sdf: Value::zero(),
            inside: Value::zero(),
            state_stack: Vec::with_capacity(8),
            hash: 1.0,
            bbox: Aabb {
                min: Vec3::zero(),
                max: Vec3::one(),
            },
            material: BSDFMaterial::default(),
            stack: Vec::with_capacity(32),
        }
    }

    pub fn execute(&mut self, code: &[NodeOp], program: &mut Program) {
        for op in code {
            match op {
                NodeOp::Load(index) => {
                    self.stack.push(self.variables[*index]);
                }
                NodeOp::Store(index) => {
                    self.variables[*index] = self.stack.pop().unwrap();
                }
                NodeOp::Swap => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(b);
                    self.stack.push(a);
                }
                NodeOp::GetComponents(swizzle) => {
                    let v = self.stack.pop().unwrap();
                    let mut result = vec![];

                    for &index in swizzle {
                        let f = match index {
                            0 => v.x(),
                            1 => v.y(),
                            2 => v.z(),
                            _ => continue,
                        };
                        result.push(f);
                    }

                    // Push as single Value: scalar or vector depending on result length
                    let pushed = match result.as_slice() {
                        [x] => Value::from_float(*x),
                        [x, y] => Value::from_vec2(Vec2::new(*x, *y)),
                        [x, y, z] => Value::from_vec3(Vec3::new(*x, *y, *z)),
                        _ => Value::from_float(0.0),
                    };

                    self.stack.push(pushed);
                }
                NodeOp::SetComponents(swizzle) => {
                    let value = self.stack.pop().unwrap();
                    let mut target = self.stack.pop().unwrap();

                    let components = match swizzle.len() {
                        1 => vec![value.x()],
                        2 => vec![value.x(), value.y()],
                        3 => vec![value.x(), value.y(), value.z()],
                        _ => vec![],
                    };

                    for (i, &idx) in swizzle.iter().enumerate() {
                        if i >= components.len() {
                            break;
                        }
                        match idx {
                            0 => target.0[0] = components[i],
                            1 => target.0[1] = components[i],
                            2 => target.0[2] = components[i],
                            _ => {}
                        }
                    }

                    self.stack.push(target);
                }
                NodeOp::Push(v) => self.stack.push(*v),
                NodeOp::Clear => _ = self.stack.pop(),
                NodeOp::Pack2 => {
                    let y = self.stack.pop().unwrap();
                    let x = self.stack.pop().unwrap();
                    self.stack.push(Value::from_components(x.x(), y.x(), 0.0));
                }
                NodeOp::Pack3 => {
                    let z = self.stack.pop().unwrap();
                    let y = self.stack.pop().unwrap();
                    let x = self.stack.pop().unwrap();
                    self.stack.push(Value::from_components(x.x(), y.x(), z.x()));
                }
                NodeOp::Dup => {
                    if let Some(top) = self.stack.last() {
                        self.stack.push(top.clone());
                    }
                }
                NodeOp::If(then_code, else_code) => {
                    let value = self.stack.pop().unwrap().truthy();
                    if value {
                        self.execute(then_code, program);
                    } else if let Some(else_code) = else_code {
                        self.execute(else_code, program);
                    }
                }
                NodeOp::IfClear(code) => {
                    if self.stack.is_empty() {
                        self.execute(code, program);
                    }
                }
                NodeOp::Place(id, at_code) => {
                    let mut at = Vec3::zero();
                    if !at_code.is_empty() {
                        self.execute(at_code, program);
                        if let Some(rc) = self.stack.pop() {
                            at = rc.as_vec3();
                        }
                    }
                    self.place(id, at, program);
                }
                NodeOp::World => {
                    self.stack.push(self.world);
                }
                NodeOp::Local => {
                    self.stack.push(self.local);
                }
                NodeOp::U => {
                    self.stack.push(self.u);
                }
                NodeOp::V => {
                    self.stack.push(self.v);
                }
                NodeOp::D => {
                    self.stack.push(self.d);
                }
                NodeOp::SDF => {
                    self.stack.push(self.sdf);
                }
                NodeOp::Inside => {
                    self.stack.push(self.inside);
                }
                NodeOp::Hash => {
                    self.stack.push(Value::from_float(self.hash));
                }
                // Math
                NodeOp::Add => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.add(b));
                }
                NodeOp::Sub => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.sub(b));
                }
                NodeOp::Mul => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.mul(b));
                }
                NodeOp::Div => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.div(b));
                }
                NodeOp::Length => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.length());
                }
                NodeOp::Abs => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.abs());
                }
                NodeOp::Sin => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_float(a.as_float().sin()));
                }
                NodeOp::Cos => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_float(a.as_float().cos()));
                }
                NodeOp::Tan => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_float(a.as_float().tan()));
                }
                NodeOp::Floor => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_float(a.as_float().floor()));
                }
                NodeOp::Ceil => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_float(a.as_float().ceil()));
                }
                NodeOp::Fract => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_float(a.as_float().fract()));
                }
                NodeOp::Mod => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_float(a.as_float() % b.as_float()));
                }
                NodeOp::Radians => {
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_float(a.as_float().to_radians()));
                }
                NodeOp::Degrees => {
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_float(a.as_float().to_degrees()));
                }
                NodeOp::Min => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.min(b));
                }
                NodeOp::Max => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.max(b));
                }
                NodeOp::Mix => {
                    let c: Value = self.stack.pop().unwrap();
                    let b: Value = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.mix(b, c));
                }
                NodeOp::Smoothstep => {
                    let c: Value = self.stack.pop().unwrap();
                    let b: Value = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.smoothstep(b, c));
                }
                NodeOp::Clamp => {
                    let c: Value = self.stack.pop().unwrap();
                    let b: Value = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.clamp(b, c));
                }
                NodeOp::SmoothUnion => {
                    let c: Value = self.stack.pop().unwrap();
                    let b: Value = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_float(self.smooth_min(
                        a.as_float(),
                        b.as_float(),
                        c.as_float(),
                    )));
                }
                NodeOp::WhiteNoise => {
                    let val = self.white_noise();
                    self.stack.push(Value::from_float(val));
                }
                NodeOp::ValueNoise => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    let val = self.value_noise(a.as_float() as i32, b.as_vec3());
                    self.hash = val;
                    self.stack.push(Value::from_float(val));
                }
                // Comparison
                NodeOp::Eq => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() == b.x()));
                }
                NodeOp::Ne => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() != b.x()));
                }
                NodeOp::Lt => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() < b.x()));
                }
                NodeOp::Le => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() <= b.x()));
                }
                NodeOp::Gt => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() > b.x()));
                }
                NodeOp::Ge => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() >= b.x()));
                }
                // Logical
                NodeOp::And => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_bool(a.x() != 0.0 && b.x() != 0.0));
                }
                NodeOp::Or => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_bool(a.x() != 0.0 || b.x() != 0.0));
                }
                // Unary
                NodeOp::Not => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() == 0.0));
                }
                NodeOp::Neg => {
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_components(-a.x(), -a.y(), -a.z()));
                }
                // Shapes
                NodeOp::ShapeRect(at, size, body) => {
                    self.push_state();

                    let bb_size = self.bbox.size();
                    let bbox_size = match self.plane {
                        Plane::XY => Vec2::new(bb_size.w, bb_size.h),
                        Plane::XZ => Vec2::new(bb_size.w, bb_size.d),
                        Plane::YZ => Vec2::new(bb_size.h, bb_size.d),
                        Plane::ZY => Vec2::new(bb_size.d, bb_size.h),
                    };

                    // --- evaluate rect size ----------------------------------------------------
                    let mut dims = bbox_size;
                    if !size.is_empty() {
                        self.execute(size, program);
                        dims = self.stack.pop().unwrap().as_vec2();
                    }

                    // --- evaluate anchor (at); default = centre (0.5, 0.5) ---------------------
                    let mut anchor = Vec2::broadcast(0.5);
                    if !at.is_empty() {
                        self.execute(at, program);
                        anchor = self.stack.pop().unwrap().as_vec2();
                    }
                    // (optional) clamp to [0,1] so weird values don’t shove the rect outside
                    anchor.x = anchor.x.clamp(0.0, 1.0);
                    anchor.y = anchor.y.clamp(0.0, 1.0);

                    // --- compute rect min per plane -------------------------------------------
                    match self.plane {
                        Plane::XY => {
                            let plane_min = Vec2::new(self.bbox.min.x, self.bbox.min.y);
                            let rect_min = plane_min + anchor * (bbox_size - dims);

                            self.bbox.min.x = rect_min.x;
                            self.bbox.min.y = rect_min.y;
                            self.bbox.max.x = rect_min.x + dims.x;
                            self.bbox.max.y = rect_min.y + dims.y;
                        }
                        Plane::XZ => {
                            let plane_min = Vec2::new(self.bbox.min.x, self.bbox.min.z);
                            let rect_min = plane_min + anchor * (bbox_size - dims);

                            self.bbox.min.x = rect_min.x;
                            self.bbox.min.z = rect_min.y;
                            self.bbox.max.x = rect_min.x + dims.x;
                            self.bbox.max.z = rect_min.y + dims.y;
                        }
                        Plane::YZ => {
                            let plane_min = Vec2::new(self.bbox.min.y, self.bbox.min.z);
                            let rect_min = plane_min + anchor * (bbox_size - dims);

                            self.bbox.min.y = rect_min.x;
                            self.bbox.min.z = rect_min.y;
                            self.bbox.max.y = rect_min.x + dims.x;
                            self.bbox.max.z = rect_min.y + dims.y;
                        }
                        Plane::ZY => {
                            let plane_min = Vec2::new(self.bbox.min.z, self.bbox.min.y);
                            let rect_min = plane_min + anchor * (bbox_size - dims);

                            self.bbox.min.z = rect_min.x;
                            self.bbox.min.y = rect_min.y;
                            self.bbox.max.z = rect_min.x + dims.x;
                            self.bbox.max.y = rect_min.y + dims.y;
                        }
                    }

                    // Execute body if local point is within new bbox
                    if self.bbox.contains_point(self.local.as_vec3()) {
                        let local = self.local.as_vec3();

                        let p = match self.plane {
                            Plane::XY => Vec2::new(
                                local.x - (self.bbox.min.x + dims.x * 0.5),
                                local.y - (self.bbox.min.y + dims.y * 0.5),
                            ),
                            Plane::XZ => Vec2::new(
                                local.x - (self.bbox.min.x + dims.x * 0.5),
                                local.z - (self.bbox.min.z + dims.y * 0.5),
                            ),
                            Plane::YZ => Vec2::new(
                                local.y - (self.bbox.min.y + dims.x * 0.5),
                                local.z - (self.bbox.min.z + dims.y * 0.5),
                            ),
                            Plane::ZY => Vec2::new(
                                local.z - (self.bbox.min.z + dims.x * 0.5),
                                local.y - (self.bbox.min.y + dims.y * 0.5),
                            ),
                        };

                        let sdf = self.sdf_box(p, dims * 0.5, 0.0);
                        self.sdf = Value::from_float(sdf);
                        self.inside = Value::from_float(-sdf);

                        self.execute(body, program);
                    }

                    self.pop_state();
                }
                NodeOp::ShapeDisc(at, radius, body) => {
                    self.push_state();

                    let mut r = 1.0;
                    if !radius.is_empty() {
                        self.execute(radius, program);
                        r = self.stack.pop().unwrap().as_float();
                    }

                    // 0.0 = flush with min side, 0.5 = centred, 1.0 = flush with max side.
                    let mut anchor = Vec2::broadcast(0.5);
                    if !at.is_empty() {
                        self.execute(at, program);
                        anchor = self.stack.pop().unwrap().as_vec2();
                    }
                    anchor.x = anchor.x.clamp(0.0, 1.0);
                    anchor.y = anchor.y.clamp(0.0, 1.0);

                    let bb_size = self.bbox.size();
                    let (plane_min, plane_size) = match self.plane {
                        Plane::XY => (
                            Vec2::new(self.bbox.min.x, self.bbox.min.y),
                            Vec2::new(bb_size.w, bb_size.h),
                        ),
                        Plane::XZ => (
                            Vec2::new(self.bbox.min.x, self.bbox.min.z),
                            Vec2::new(bb_size.w, bb_size.d),
                        ),
                        Plane::YZ => (
                            Vec2::new(self.bbox.min.y, self.bbox.min.z),
                            Vec2::new(bb_size.h, bb_size.d),
                        ),
                        Plane::ZY => (
                            Vec2::new(self.bbox.min.z, self.bbox.min.y),
                            Vec2::new(bb_size.d, bb_size.h),
                        ),
                    };

                    let offset = plane_min
                        + anchor * (plane_size - Vec2::broadcast(2.0 * r))
                        + Vec2::broadcast(r);

                    match self.plane {
                        Plane::XY => {
                            self.bbox.min.x = offset.x - r;
                            self.bbox.max.x = offset.x + r;
                            self.bbox.min.y = offset.y - r;
                            self.bbox.max.y = offset.y + r;
                        }
                        Plane::XZ => {
                            self.bbox.min.x = offset.x - r;
                            self.bbox.max.x = offset.x + r;
                            self.bbox.min.z = offset.y - r;
                            self.bbox.max.z = offset.y + r;
                        }
                        Plane::YZ => {
                            self.bbox.min.y = offset.x - r;
                            self.bbox.max.y = offset.x + r;
                            self.bbox.min.z = offset.y - r;
                            self.bbox.max.z = offset.y + r;
                        }
                        Plane::ZY => {
                            self.bbox.min.z = offset.x - r;
                            self.bbox.max.z = offset.x + r;
                            self.bbox.min.y = offset.y - r;
                            self.bbox.max.y = offset.y + r;
                        }
                    }

                    if self.bbox.contains_point(self.local.as_vec3()) {
                        let local = self.local.as_vec3();

                        let (p, h) = match self.plane {
                            Plane::XY => {
                                (Vec2::new(local.x - offset.x, local.y - offset.y), local.z)
                            }
                            Plane::XZ => {
                                (Vec2::new(local.x - offset.x, local.z - offset.y), local.y)
                            }
                            Plane::YZ => {
                                (Vec2::new(local.y - offset.x, local.z - offset.y), local.x)
                            }
                            Plane::ZY => {
                                (Vec2::new(local.z - offset.x, local.y - offset.y), local.x)
                            }
                        };

                        let theta = p.y.atan2(p.x);
                        let rlen = p.magnitude();
                        let sdf = rlen - r;

                        use std::f32::consts::TAU;

                        let repeats = 5.0;
                        let u = (theta / TAU * repeats + repeats * 0.5).fract();

                        self.u = Value::from_float(u);
                        self.v = Value::from_float(h.abs());
                        self.sdf = Value::from_float(sdf);
                        self.inside = Value::from_float(-sdf);

                        if sdf <= 0.0 {
                            self.execute(body, program);
                        }
                    }

                    self.pop_state();
                }
                // Segments
                NodeOp::SegmentLeft(depth, body) => {
                    self.push_state();

                    self.plane = Plane::ZY;
                    let local = self.local.as_vec3();

                    let thickness = if depth.is_empty() {
                        0.1
                    } else {
                        self.execute(depth, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.bbox.max.x = self.bbox.min.x + thickness;
                    if self.bbox.contains_point(local) {
                        self.u = Value::from_float(local.z - self.bbox.min.z); // u = Z
                        self.v = Value::from_float(local.y - self.bbox.min.y); // v = Y
                        self.d = Value::from_float(local.x - self.bbox.min.x); // d = X (depth)

                        self.execute(body, program);
                    }

                    self.pop_state();
                }
                NodeOp::SegmentBack(depth, body) => {
                    self.push_state();

                    self.plane = Plane::XY;
                    let local = self.local.as_vec3();

                    let thickness = if depth.is_empty() {
                        0.1
                    } else {
                        self.execute(depth, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.bbox.max.z = self.bbox.min.z + thickness;
                    if self.bbox.contains_point(local) {
                        self.u = Value::from_float(local.x - self.bbox.min.x); // u = X
                        self.v = Value::from_float(local.y - self.bbox.min.y); // v = Y
                        self.d = Value::from_float(local.z - self.bbox.min.z); // d = Z (depth)

                        self.execute(body, program);
                    }

                    self.pop_state();
                }
                NodeOp::SegmentFloor(depth, body) => {
                    self.push_state();

                    self.plane = Plane::XZ;
                    let local = self.local.as_vec3();

                    let thickness = if depth.is_empty() {
                        0.1
                    } else {
                        self.execute(depth, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.bbox.max.y = self.bbox.min.y + thickness;
                    if self.bbox.contains_point(local) {
                        self.u = Value::from_float(local.x - self.bbox.min.x); // u = X
                        self.v = Value::from_float(local.z - self.bbox.min.z); // v = Z
                        self.d = Value::from_float(local.y - self.bbox.min.y); // d = Y (depth from floor)

                        self.execute(body, program);
                    }

                    self.pop_state();
                }
                NodeOp::SegmentRight(depth, body) => {
                    self.push_state();

                    self.plane = Plane::ZY;
                    let local = self.local.as_vec3();

                    let thickness = if depth.is_empty() {
                        0.1
                    } else {
                        self.execute(depth, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.bbox.min.x = self.bbox.max.x - thickness;
                    if self.bbox.contains_point(local) {
                        self.u = Value::from_float(local.z - self.bbox.min.z); // u = Z
                        self.v = Value::from_float(local.y - self.bbox.min.y); // v = Y
                        self.d = Value::from_float(self.bbox.max.x - local.x); // d = X (depth)
                        self.execute(body, program);
                    }

                    self.pop_state();
                }
                NodeOp::SegmentFront(depth, body) => {
                    self.push_state();

                    self.plane = Plane::XY;
                    let local = self.local.as_vec3();

                    let thickness = if depth.is_empty() {
                        0.1
                    } else {
                        self.execute(depth, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.bbox.min.z = self.bbox.max.z - thickness;
                    if self.bbox.contains_point(local) {
                        self.u = Value::from_float(local.x - self.bbox.min.x); // u = X
                        self.v = Value::from_float(local.y - self.bbox.min.y); // v = Y
                        self.d = Value::from_float(self.bbox.max.z - local.z); // d = Z (depth)
                        self.execute(body, program);
                    }

                    self.pop_state();
                }
                NodeOp::SegmentCeiling(depth, body) => {
                    self.push_state();

                    self.plane = Plane::XZ;
                    let local = self.local.as_vec3();

                    let thickness = if depth.is_empty() {
                        0.1
                    } else {
                        self.execute(depth, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.bbox.min.y = self.bbox.max.y - thickness;
                    if self.bbox.contains_point(local) {
                        self.u = Value::from_float(local.x - self.bbox.min.x); // u = X
                        self.v = Value::from_float(local.z - self.bbox.min.z); // v = Z
                        self.d = Value::from_float(self.bbox.max.y - local.y); // d = Y (depth)
                        self.execute(body, program);
                    }

                    self.pop_state();
                }
                // Pattern
                NodeOp::PatternModulo(size, even, odd) => {
                    let u = self.u.as_float();
                    let v = self.v.as_float();

                    let modulo_size = if size.is_empty() {
                        0.02
                    } else {
                        self.execute(size, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    let cell_u = (u / modulo_size).floor() as i32;
                    let cell_v = (v / modulo_size).floor() as i32;

                    // Set `self.hash` based on cell ID
                    let cell_id = Vec2::new(cell_u as f32, cell_v as f32);
                    self.hash = (self.hash21(cell_id) + 1.0) * 0.5;

                    let is_even = (cell_u ^ cell_v) % 2 == 0;
                    if is_even {
                        if let Some(even) = even {
                            self.execute(even, program);
                        }
                    } else {
                        if let Some(odd) = odd {
                            self.execute(odd, program);
                        }
                    }
                }
                NodeOp::PatternBricks(size, gap, round, br, ce) => {
                    let brick_size = if size.is_empty() {
                        Vec2::new(0.3, 0.1)
                    } else {
                        self.execute(size, program);
                        self.stack.pop().unwrap().as_vec2()
                    };
                    let gap_size = if gap.is_empty() {
                        0.02
                    } else {
                        self.execute(gap, program);
                        self.stack.pop().unwrap().as_float()
                    };
                    let rounding = if round.is_empty() {
                        0.1
                    } else {
                        self.execute(round, program);
                        self.stack.pop().unwrap().as_float()
                    };
                    let cell = brick_size + Vec2::broadcast(gap_size);

                    let mut u = Vec2::new(self.u.x(), self.v.x()) / cell;
                    u.x += 0.5 * ((u.y.floor() as i32 % 2) as f32);

                    let cell_id = u.map(|v| v.floor());
                    self.hash = (self.hash21(cell_id) + 1.0) * 0.5;

                    let p = u.map(|v| v.fract()) - 0.5;
                    let rc = self.sdf_box(p, brick_size / cell * 0.5, rounding);

                    if rc < 0.0 {
                        if let Some(br) = br {
                            self.execute(br, program);
                        }
                    } else {
                        if let Some(ce) = ce {
                            self.execute(ce, program);
                        }
                    }
                }
                // Material Write Instructions
                NodeOp::MaterialAlbedo => {
                    if let Some(top) = self.stack.last() {
                        self.material.base_color = top.as_vec3();
                    }
                }
                NodeOp::MaterialSubsurface => {
                    if let Some(top) = self.stack.last() {
                        self.material.subsurface = top.as_float();
                    }
                }
                NodeOp::MaterialMetallic => {
                    if let Some(top) = self.stack.last() {
                        self.material.metallic = top.as_float();
                    }
                }
                NodeOp::MaterialSpecularTint => {
                    if let Some(top) = self.stack.last() {
                        self.material.specular_tint = top.as_float();
                    }
                }
                NodeOp::MaterialRoughness => {
                    if let Some(top) = self.stack.last() {
                        self.material.roughness = top.as_float();
                    }
                }
                NodeOp::MaterialAnisotropic => {
                    if let Some(top) = self.stack.last() {
                        self.material.anisotropic = top.as_float();
                    }
                }
                NodeOp::MaterialSheen => {
                    if let Some(top) = self.stack.last() {
                        self.material.sheen = top.as_float();
                    }
                }
                NodeOp::MaterialSheenTint => {
                    if let Some(top) = self.stack.last() {
                        self.material.sheen_tint = top.as_float();
                    }
                }
                NodeOp::MaterialClearcoat => {
                    if let Some(top) = self.stack.last() {
                        self.material.clearcoat = top.as_float();
                    }
                }
                NodeOp::MaterialClearcoatGloss => {
                    if let Some(top) = self.stack.last() {
                        self.material.clearcoat_roughness = top.as_float();
                    }
                }
                NodeOp::MaterialIOR => {
                    if let Some(top) = self.stack.last() {
                        self.material.ior = top.as_float();
                    }
                }
                NodeOp::MaterialTransmission => {
                    if let Some(top) = self.stack.last() {
                        self.material.spec_trans = top.as_float();
                    }
                }
                NodeOp::MaterialEmission => {
                    if let Some(top) = self.stack.last() {
                        self.material.emission = top.as_vec3();
                    }
                }
            }
        }
    }

    /// Place a voxel box into the world. We first model into a separate grid
    /// and than merge back into the program grid.
    pub fn place(&mut self, id: &String, at: Vec3<f32>, program: &mut Program) {
        let voxel = match program.voxels.get(id) {
            Some(defined) => defined.clone(),
            None => return,
        };

        let mut grid = VoxelGrid::empty(program.grid.read().unwrap().density);

        let mut execution = Execution::new_from_var(&self);
        let mut size = Vec3::new(1.0, 1.0, 1.0);
        execution.execute(&voxel.size, program);
        if let Some(value) = execution.stack.last() {
            size = value.as_vec3();
        }

        let rect = VoxelRect {
            origin: at - size * 0.5,
            size,
        };

        let voxel_size = 1.0 / grid.density_f;

        let tile_min = (
            rect.origin.x.floor() as i32,
            rect.origin.y.floor() as i32,
            rect.origin.z.floor() as i32,
        );
        let tile_max = (
            (rect.origin.x + rect.size.x).ceil() as i32 - 1,
            (rect.origin.y + rect.size.y).ceil() as i32 - 1,
            (rect.origin.z + rect.size.z).ceil() as i32 - 1,
        );

        let tile_keys: Vec<Coord> = (tile_min.2..=tile_max.2)
            .flat_map(|tz| {
                (tile_min.1..=tile_max.1)
                    .flat_map(move |ty| (tile_min.0..=tile_max.0).map(move |tx| (tx, ty, tz)))
            })
            .collect();

        let aabb = Aabb {
            min: -size * 0.5,
            max: size * 0.5,
        };

        let produced: Vec<(Coord, Tile)> = tile_keys
            .into_par_iter()
            .map(|tile_key| {
                let mut tile = Tile::new(grid.density);
                let tile_origin = Vec3::new(tile_key.0 as F, tile_key.1 as F, tile_key.2 as F);

                let mut exec = Execution::new_from_var(self);
                let mut p = Program::new(Vec3::zero(), grid.density);

                for z in 0..grid.density {
                    for y in 0..grid.density {
                        for x in 0..grid.density {
                            let world = (tile_origin
                                + Vec3::new(x as F, y as F, z as F) / grid.density_f)
                                + Vec3::broadcast(voxel_size * 0.5);

                            // let world = world_abs - center;
                            let local = world - at;

                            exec.stack.clear();
                            exec.world = Value::from_vec3(world);
                            exec.local = Value::from_vec3(local);
                            exec.bbox = aabb;

                            exec.execute(&voxel.body, &mut p);
                            if let Some(val) = exec.stack.last() {
                                let mat = val.x();
                                if mat >= 0.0 {
                                    let hash = (exec.hash * 255.0).floor() as u8;
                                    tile.set(
                                        (x as i32, y as i32, z as i32),
                                        Voxel::new(mat as u8, hash),
                                    );
                                }
                            }
                        }
                    }
                }

                let grid_offset = (rect.origin + rect.size * 0.5).map(|v| v.floor() as i32);
                let tile_key_offset = (
                    tile_key.0 + grid_offset.x,
                    tile_key.1 + grid_offset.y,
                    tile_key.2 + grid_offset.z,
                );

                (tile_key_offset, tile)
            })
            .collect();

        for (key, tile) in produced {
            grid.tiles.insert(key, tile);
        }

        program.grid.write().unwrap().merge(&grid);
    }

    /// SDF to a Hexagon
    #[inline]
    fn _sdf_hex(p: Vec2<f32>, radius: f32) -> f32 {
        let k = Vec2::new(-0.8660254, 0.5); // cos(π/6), sin(π/6)
        let p = p.map(|v| v.abs());

        let a = p - k * (p.dot(k)).min(radius);
        let b = p - Vec2::new(radius, 0.0);
        let inside = if p.y > radius * 0.5 { a } else { b };

        inside.magnitude() * inside.y.signum()
    }

    /// SDF to a 2D box
    #[inline]
    fn sdf_box(&self, p: Vec2<f32>, b: Vec2<f32>, r: f32) -> f32 {
        let d = p.map(|v| v.abs()) - b + Vec2::broadcast(r);
        d.x.max(d.y).min(0.0) + (d.map(|v| v.max(0.0))).magnitude() - r
    }

    /// Hash21
    #[inline]
    fn hash21(&self, p: Vec2<f32>) -> f32 {
        let dot = p.x * 127.1 + p.y * 311.7;
        (dot.sin().fract() * 43758.5453).fract()
    }

    #[inline]
    fn smooth_min(&self, a: f32, b: f32, k: f32) -> f32 {
        let h = (0.5 + 0.5 * (b - a) / k).clamp(0.0, 1.0);
        let m = b * (1.0 - h) + a * h;
        m - k * h * (1.0 - h)
    }

    #[inline]
    fn white_noise(&self) -> f32 {
        let p = self.local.as_vec3();

        let dot = (p.x + p.z) * 127.1 + (p.y + p.z) * 311.7 + (p.x + p.y) * 74.7;
        (dot.sin() * 43758.5453).fract()
    }

    /// Value noise 3D
    /// Base on https://www.shadertoy.com/view/4dS3Wd
    fn value_noise(&self, octaves: i32, scale: Vec3<f32>) -> f32 {
        fn hash(mut p: f32) -> f32 {
            p = (p * 0.011).fract();
            p *= p + 7.5;
            p *= p + p;
            p.fract()
        }

        fn noise(x: Vec3<f32>) -> f32 {
            let step = Vec3::new(110.0, 241.0, 171.0);

            let i = x.map(|v| v.floor());
            let f = x.map(|v| v.fract());

            let n = i.dot(step);

            let u = f * f * f.map(|v| 3.0 - 2.0 * v);

            lerp(
                lerp(
                    lerp(
                        hash(n + step.dot(Vec3::new(0.0, 0.0, 0.0))),
                        hash(n + step.dot(Vec3::new(1.0, 0.0, 0.0))),
                        u.x,
                    ),
                    lerp(
                        hash(n + step.dot(Vec3::new(0.0, 1.0, 0.0))),
                        hash(n + step.dot(Vec3::new(1.0, 1.0, 0.0))),
                        u.x,
                    ),
                    u.y,
                ),
                lerp(
                    lerp(
                        hash(n + step.dot(Vec3::new(0.0, 0.0, 1.0))),
                        hash(n + step.dot(Vec3::new(1.0, 0.0, 1.0))),
                        u.x,
                    ),
                    lerp(
                        hash(n + step.dot(Vec3::new(0.0, 1.0, 1.0))),
                        hash(n + step.dot(Vec3::new(1.0, 1.0, 1.0))),
                        u.x,
                    ),
                    u.y,
                ),
                u.z,
            )
        }

        let p = self.local.as_vec3();

        let mut x = Vec3::new(1240.0, 1240.0, 1240.0) + p * 8.0 * scale;

        if octaves == 0 {
            return noise(x);
        }

        let mut v = 0.0;
        let mut a = 0.5;
        let shift = Vec3::new(100.0, 100.0, 100.0);
        for _ in 0..octaves {
            v += a * noise(x);
            x = x * 2.0 + shift;
            a *= 0.5;
        }
        v
    }

    // Push the current segmentation state.
    fn push_state(&mut self) {
        self.state_stack.push(SegmentationState {
            bbox: self.bbox.clone(),
            plane: self.plane,
            u: self.u,
            v: self.v,
            d: self.d,
            sdf: self.sdf,
            inside: self.inside,
        });
    }

    // Pop the last segmentation state.
    fn pop_state(&mut self) {
        if let Some(state) = self.state_stack.pop() {
            self.bbox = state.bbox;
            self.plane = state.plane;
            self.u = state.u;
            self.v = state.v;
            self.d = state.d;
            self.sdf = state.sdf;
            self.inside = state.inside;
        }
    }
}
