use crate::prelude::*;
pub mod execution;
pub mod program;
pub mod value;

#[derive(Clone, Copy, Debug)]
pub enum Plane {
    XY, // Back, Front
    YZ,
    XZ, // Floor, Ceiling
    ZY, // Left, Right
}

#[derive(Debug, Clone)]
pub enum NodeOp {
    Load(usize),
    Store(usize),
    Swap,
    GetComponents(Vec<u8>),
    SetComponents(Vec<u8>),
    If(Vec<NodeOp>, Option<Vec<NodeOp>>),
    IfClear(Vec<NodeOp>),
    Place(String, Vec<NodeOp>),
    Push(Value),
    Clear,
    Dup,
    World,
    Local,
    U,
    V,
    D,
    SDF,
    Inside,
    Hash,
    Pack2,
    Pack3,
    Add,
    Sub,
    Mul,
    Div,
    Length,
    Abs,
    Sin,
    Cos,
    Tan,
    Atan,
    Atan2,
    Dot,
    Cross,
    Normalize,
    Floor,
    Ceil,
    Fract,
    Mod,
    Degrees,
    Radians,
    Min,
    Max,
    Mix,
    Smoothstep,
    Step,
    Clamp,
    Sqrt,
    Pow,
    Log,
    SmoothUnion,
    WhiteNoise,
    ValueNoise,
    PointAt,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    And,
    Or,
    Not,
    Neg,
    ShapeRect(Vec<NodeOp>, Vec<NodeOp>, Vec<NodeOp>),
    ShapeDisc(Vec<NodeOp>, Vec<NodeOp>, Vec<NodeOp>),
    SegmentLeft(Vec<NodeOp>, Vec<NodeOp>),
    SegmentBack(Vec<NodeOp>, Vec<NodeOp>),
    SegmentFloor(Vec<NodeOp>, Vec<NodeOp>),
    SegmentRight(Vec<NodeOp>, Vec<NodeOp>),
    SegmentFront(Vec<NodeOp>, Vec<NodeOp>),
    SegmentCeiling(Vec<NodeOp>, Vec<NodeOp>),
    PatternModulo(Vec<NodeOp>, Option<Vec<NodeOp>>, Option<Vec<NodeOp>>),
    PatternBricks(
        Vec<NodeOp>,
        Vec<NodeOp>,
        Vec<NodeOp>,
        Option<Vec<NodeOp>>,
        Option<Vec<NodeOp>>,
    ),
    DistanceSphere(Vec<NodeOp>, Vec<NodeOp>, Vec<NodeOp>),
    DistanceBox(Vec<NodeOp>, Vec<NodeOp>, Vec<NodeOp>, Vec<NodeOp>),
    DistanceCapsule(Vec<NodeOp>, Vec<NodeOp>, Vec<NodeOp>, Vec<NodeOp>),
    DistanceCylinder(Vec<NodeOp>, Vec<NodeOp>, Vec<NodeOp>, Vec<NodeOp>),
    DistanceCone(
        Vec<NodeOp>,
        Vec<NodeOp>,
        Vec<NodeOp>,
        Vec<NodeOp>,
        Vec<NodeOp>,
    ),
    DistanceVesica(Vec<NodeOp>, Vec<NodeOp>, Vec<NodeOp>, Vec<NodeOp>),
    DistancePyramid(
        Vec<NodeOp>,
        Vec<NodeOp>,
        Vec<NodeOp>,
        Vec<NodeOp>,
        Vec<NodeOp>,
    ),
    DistanceNgonFrustum(
        Vec<NodeOp>,
        Vec<NodeOp>,
        Vec<NodeOp>,
        Vec<NodeOp>,
        Vec<NodeOp>,
        Vec<NodeOp>,
        Vec<NodeOp>,
    ),
    DistanceBoxBetween(
        Vec<NodeOp>,
        Vec<NodeOp>,
        Vec<NodeOp>,
        Vec<NodeOp>,
        Vec<NodeOp>,
        Vec<NodeOp>,
    ),
    Volume(Vec<NodeOp>),
    MaterialAlbedo,
    MaterialSubsurface,
    MaterialMetallic,
    MaterialSpecularTint,
    MaterialRoughness,
    MaterialAnisotropic,
    MaterialSheen,
    MaterialSheenTint,
    MaterialClearcoat,
    MaterialClearcoatGloss,
    MaterialIOR,
    MaterialTransmission,
    MaterialEmission,
    MediumAbsorb,
    MediumScatter,
    MediumEmissive,
    MediumDensity,
    MediumAnisotropy,
    MediumColor,
}
