[package]
name = "shpz"
edition = "2024"
version = "0.8.23"
license = "MIT"
authors = ["Markus Moenig"]
description = "Shape Prozessing Language"

[[bin]]
name = "shpz"
path = "src/main.rs"

[dependencies]

rayon = "1"
vek = { version = "0.17.1", default-features = true }
rand = "0.9"
num_cpus = "1.16.0"
rustc-hash = "1.1.0"
image = "0.25.1"
indexmap = "2.10.0"

[dependencies.uuid]
version = "1.17.0"
features = ["v4"]
