[package]
name = "shapezlib"
edition = "2021"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Markus Moenig"]
description = "Shape Prozessing Language"
keywords = ["language", "voxel", "rendering", "procedural", "modeling"]
repository = "https://github.com/markusmoenig/Shape-Z.git"
homepage = "https://shape-z.com"

[dependencies]
image = { version = "0.25", features = ["png"] }
indexmap = "2.10.0"
rayon = "1"
vek = { version = "0.17.1", default-features = true }
rand = "0.9"
rustc-hash = "1.1.0"
fast-surface-nets = "0.2.1"
getrandom = { version = "0.3.3", features = ["wasm_js"] }
wasm-bindgen = "0.2"
wasm-bindgen-rayon = { version = "1.3", features = ["no-bundler"] }
rust-embed = { version = "8", default-features = true, features = [
    "include-exclude",
] }

# [lib]
# crate-type = ["cdylib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.7"
web-sys = { version = "0.3", features = ["Window", "Performance", "console"] }
js-sys = "0.3"
