use crate::prelude::*;

pub struct Execution {
    pub variables: Vec<Value>,

    /// The world coordinate of the current voxel
    pub world: Value,
    /// The segment transformed local coordinate
    pub local: Value,
    /// The segment computed u value
    pub u: Value,
    /// The segment computed v value
    pub v: Value,
    /// The segment computed d (depth) value
    pub d: Value,

    /// Hash, generated by patterns and passed on to the materials.
    pub hash: f32,

    /// The current bbox of the model space. Gets subdivided by segments during
    /// execution.
    pub bbox: Aabb<f32>,

    /// The material the VM writes to.
    pub material: Material,

    /// The execution stack.
    pub stack: Vec<Value>,
}

impl Execution {
    pub fn new(var_size: usize) -> Self {
        Self {
            variables: vec![Value::zero(); var_size],
            world: Value::zero(),
            local: Value::zero(),
            u: Value::zero(),
            v: Value::zero(),
            d: Value::zero(),
            hash: 1.0,
            bbox: Aabb {
                min: Vec3::zero(),
                max: Vec3::one(),
            },
            material: Material::default(),
            stack: Vec::with_capacity(32),
        }
    }

    pub fn new_from_var(execution: &Execution) -> Self {
        Self {
            variables: execution.variables.clone(),
            world: Value::zero(),
            local: Value::zero(),
            u: Value::zero(),
            v: Value::zero(),
            d: Value::zero(),
            hash: 1.0,
            bbox: Aabb {
                min: Vec3::zero(),
                max: Vec3::one(),
            },
            material: Material::default(),
            stack: Vec::with_capacity(32),
        }
    }

    pub fn execute(&mut self, code: &[NodeOp], program: &mut Program) {
        for op in code {
            match op {
                NodeOp::Load(index) => {
                    self.stack.push(self.variables[*index]);
                }
                NodeOp::Store(index) => {
                    self.variables[*index] = self.stack.pop().unwrap();
                }
                NodeOp::Swap => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(b);
                    self.stack.push(a);
                }
                NodeOp::GetComponents(swizzle) => {
                    let v = self.stack.pop().unwrap();
                    let mut result = vec![];

                    for &index in swizzle {
                        let f = match index {
                            0 => v.x(),
                            1 => v.y(),
                            2 => v.z(),
                            _ => continue,
                        };
                        result.push(f);
                    }

                    // Push as single Value: scalar or vector depending on result length
                    let pushed = match result.as_slice() {
                        [x] => Value::from_float(*x),
                        [x, y] => Value::from_vec2(Vec2::new(*x, *y)),
                        [x, y, z] => Value::from_vec3(Vec3::new(*x, *y, *z)),
                        _ => Value::from_float(0.0),
                    };

                    self.stack.push(pushed);
                }
                NodeOp::SetComponents(swizzle) => {
                    let value = self.stack.pop().unwrap();
                    let mut target = self.stack.pop().unwrap();

                    let components = match swizzle.len() {
                        1 => vec![value.x()],
                        2 => vec![value.x(), value.y()],
                        3 => vec![value.x(), value.y(), value.z()],
                        _ => vec![],
                    };

                    for (i, &idx) in swizzle.iter().enumerate() {
                        if i >= components.len() {
                            break;
                        }
                        match idx {
                            0 => target.0[0] = components[i],
                            1 => target.0[1] = components[i],
                            2 => target.0[2] = components[i],
                            _ => {}
                        }
                    }

                    self.stack.push(target);
                }
                NodeOp::Push(v) => self.stack.push(*v),
                NodeOp::Pack3 => {
                    let z = self.stack.pop().unwrap();
                    let y = self.stack.pop().unwrap();
                    let x = self.stack.pop().unwrap();
                    self.stack.push(Value::from_components(x.x(), y.x(), z.x()));
                }
                NodeOp::Dup => {
                    if let Some(top) = self.stack.last() {
                        self.stack.push(top.clone());
                    }
                }
                NodeOp::If(then_code, else_code) => {
                    let value = self.stack.pop().unwrap().truthy();
                    if value {
                        self.execute(then_code, program);
                    } else if let Some(else_code) = else_code {
                        self.execute(else_code, program);
                    }
                }
                NodeOp::Place(id) => self.place(id, program),
                NodeOp::World => {
                    self.stack.push(self.world);
                }
                NodeOp::Local => {
                    self.stack.push(self.local);
                }
                NodeOp::U => {
                    self.stack.push(self.u);
                }
                NodeOp::V => {
                    self.stack.push(self.v);
                }
                NodeOp::D => {
                    self.stack.push(self.d);
                }
                NodeOp::Hash => {
                    self.stack.push(Value::from_float(self.hash));
                }
                // Math
                NodeOp::Add => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.add(b));
                }
                NodeOp::Sub => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.sub(b));
                }
                NodeOp::Mul => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.mul(b));
                }
                NodeOp::Div => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.div(b));
                }
                NodeOp::Length => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.length());
                }
                NodeOp::Abs => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(a.abs());
                }
                NodeOp::Sin => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_float(a.as_float().sin()));
                }
                NodeOp::Cos => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_float(a.as_float().cos()));
                }
                NodeOp::Tan => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_float(a.as_float().tan()));
                }
                NodeOp::Floor => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_float(a.as_float().floor()));
                }
                NodeOp::Ceil => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_float(a.as_float().ceil()));
                }
                NodeOp::Fract => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_float(a.as_float().fract()));
                }
                NodeOp::Mod => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_float(a.as_float() % b.as_float()));
                }
                NodeOp::Radians => {
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_float(a.as_float().to_radians()));
                }
                NodeOp::Degrees => {
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_float(a.as_float().to_degrees()));
                }
                // Comparison
                NodeOp::Eq => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() == b.x()));
                }
                NodeOp::Ne => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() != b.x()));
                }
                NodeOp::Lt => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() < b.x()));
                }
                NodeOp::Le => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() <= b.x()));
                }
                NodeOp::Gt => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() > b.x()));
                }
                NodeOp::Ge => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() >= b.x()));
                }
                // Logical
                NodeOp::And => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_bool(a.x() != 0.0 && b.x() != 0.0));
                }
                NodeOp::Or => {
                    let b = self.stack.pop().unwrap();
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_bool(a.x() != 0.0 || b.x() != 0.0));
                }
                // Unary
                NodeOp::Not => {
                    let a = self.stack.pop().unwrap();
                    self.stack.push(Value::from_bool(a.x() == 0.0));
                }
                NodeOp::Neg => {
                    let a = self.stack.pop().unwrap();
                    self.stack
                        .push(Value::from_components(-a.x(), -a.y(), -a.z()));
                }
                // Shapes
                NodeOp::ShapeRect(body) => {
                    let cl = self.bbox.clone();
                    self.execute(body, program);
                    self.bbox = cl;
                }
                NodeOp::ShapeDisc(body) => {
                    let local = self.local.as_vec3();

                    // Get center and radius from bbox in XZ plane
                    let bbox = &self.bbox;
                    let center_x = (bbox.min.x + bbox.max.x) * 0.5;
                    let center_z = (bbox.min.z + bbox.max.z) * 0.5;
                    let radius_x = (bbox.max.x - bbox.min.x) * 0.5;
                    let radius_z = (bbox.max.z - bbox.min.z) * 0.5;
                    let radius = radius_x.min(radius_z); // use smallest to stay inside bounds

                    let dx = local.x - center_x;
                    let dz = local.z - center_z;
                    let r = (dx * dx + dz * dz).sqrt();

                    if r > radius {
                        return;
                    }

                    let theta = dz.atan2(dx); // angle around Y axis (radians)
                    let height = local.y;

                    self.u = Value::from_float(theta); // angle in radians
                    self.v = Value::from_float(height); // Y height
                    self.d = Value::from_float(r); // radial depth

                    let bbox_backup = self.bbox.clone();
                    self.execute(body, program);
                    self.bbox = bbox_backup;
                }
                // Segments
                NodeOp::SegmentLeft(depth, body) => {
                    let old_max_x = self.bbox.max.x;

                    let local = self.local.as_vec3();

                    let thickness = if depth.is_empty() {
                        0.1
                    } else {
                        self.execute(depth, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.bbox.max.x = self.bbox.min.x + thickness;
                    if self.bbox.contains_point(local) {
                        self.u = Value::from_float(local.z - self.bbox.min.z); // u = Z
                        self.v = Value::from_float(local.y - self.bbox.min.y); // v = Y
                        self.d = Value::from_float(local.x - self.bbox.min.x); // d = X (depth)

                        self.execute(body, program);
                    }

                    self.bbox.max.x = old_max_x;
                }
                NodeOp::SegmentBack(depth, body) => {
                    let old_max_z = self.bbox.max.z;

                    let local = self.local.as_vec3();

                    let thickness = if depth.is_empty() {
                        0.1
                    } else {
                        self.execute(depth, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.bbox.max.z = self.bbox.min.z + thickness;
                    if self.bbox.contains_point(local) {
                        self.u = Value::from_float(local.x - self.bbox.min.x); // u = X
                        self.v = Value::from_float(local.y - self.bbox.min.y); // v = Y
                        self.d = Value::from_float(local.z - self.bbox.min.z); // d = Z (depth)

                        self.execute(body, program);
                    }

                    self.bbox.max.z = old_max_z;
                }
                NodeOp::SegmentFloor(depth, body) => {
                    let old_max_y = self.bbox.max.y;

                    let local = self.local.as_vec3();

                    let thickness = if depth.is_empty() {
                        0.1
                    } else {
                        self.execute(depth, program);
                        self.stack.pop().unwrap().as_float()
                    };

                    self.bbox.max.y = self.bbox.min.y + thickness;
                    if self.bbox.contains_point(local) {
                        self.u = Value::from_float(local.x - self.bbox.min.x); // u = X
                        self.v = Value::from_float(local.z - self.bbox.min.z); // v = Z
                        self.d = Value::from_float(local.y - self.bbox.min.y); // d = Y (depth from floor)

                        self.execute(body, program);
                    }

                    self.bbox.max.y = old_max_y;
                }
                // Pattern
                NodeOp::PatternModulo(even, odd) => {
                    let u = self.u.as_float();
                    let v = self.v.as_float();

                    let size = 0.1;

                    let cell_u = (u / size).floor() as i32;
                    let cell_v = (v / size).floor() as i32;

                    let is_even = (cell_u ^ cell_v) % 2 == 0;
                    if is_even {
                        if let Some(even) = even {
                            self.execute(even, program);
                        }
                    } else {
                        if let Some(odd) = odd {
                            self.execute(odd, program);
                        }
                    }
                }
                NodeOp::PatternBricks(br, ce) => {
                    fn s_box(p: Vec2<f32>, b: Vec2<f32>, r: f32) -> f32 {
                        let d = p.map(|v| v.abs()) - b + Vec2::new(r, r);
                        d.x.max(d.y).min(0.0) + (d.map(|v| v.max(0.0))).magnitude() - r
                    }
                    fn hash21(p: Vec2<f32>) -> f32 {
                        let dot = p.x * 127.1 + p.y * 311.7;
                        (dot.sin().fract() * 43758.5453).fract()
                    }

                    let round = 0.1;
                    let brick_size = Vec2::new(0.3, 0.1);
                    let gap = 0.02;
                    let cell = brick_size + Vec2::broadcast(gap);

                    let mut u = Vec2::new(self.u.x(), self.v.x()) / cell;
                    u.x += 0.5 * ((u.y.floor() as i32 % 2) as f32);

                    let cell_id = u.map(|v| v.floor());
                    self.hash = (hash21(cell_id) + 1.0) * 0.5;

                    let p = u.map(|v| v.fract()) - 0.5;
                    let rc = s_box(p, brick_size / cell * 0.5, round);

                    if rc < 0.0 {
                        if let Some(br) = br {
                            self.execute(br, program);
                        }
                    } else {
                        if let Some(ce) = ce {
                            self.execute(ce, program);
                        }
                    }
                }
                // Material Write Instructions
                NodeOp::MaterialAlbedo => {
                    if let Some(top) = self.stack.last() {
                        self.material.base_color = top.as_vec3();
                    }
                }
                NodeOp::MaterialSubsurface => {
                    if let Some(top) = self.stack.last() {
                        self.material.subsurface = top.as_float();
                    }
                }
                NodeOp::MaterialMetallic => {
                    if let Some(top) = self.stack.last() {
                        self.material.metallic = top.as_float();
                    }
                }
                NodeOp::MaterialSpecular => {
                    if let Some(top) = self.stack.last() {
                        self.material.specular = top.as_float();
                    }
                }
                NodeOp::MaterialRoughness => {
                    if let Some(top) = self.stack.last() {
                        self.material.roughness = top.as_float();
                    }
                }
                NodeOp::MaterialAnisotropic => {
                    if let Some(top) = self.stack.last() {
                        self.material.anisotropic = top.as_float();
                    }
                }
                NodeOp::MaterialSheen => {
                    if let Some(top) = self.stack.last() {
                        self.material.sheen = top.as_float();
                    }
                }
                NodeOp::MaterialSheenTint => {
                    if let Some(top) = self.stack.last() {
                        self.material.sheen_tint = top.as_float();
                    }
                }
                NodeOp::MaterialClearcoat => {
                    if let Some(top) = self.stack.last() {
                        self.material.clearcoat = top.as_float();
                    }
                }
                NodeOp::MaterialClearcoatGloss => {
                    if let Some(top) = self.stack.last() {
                        self.material.clearcoat_gloss = top.as_float();
                    }
                }
                NodeOp::MaterialIOR => {
                    if let Some(top) = self.stack.last() {
                        self.material.ior = top.as_float();
                    }
                }
                NodeOp::MaterialTransmission => {
                    if let Some(top) = self.stack.last() {
                        self.material.transmission = top.as_float();
                    }
                }
                NodeOp::MaterialTransmissionRoughness => {
                    if let Some(top) = self.stack.last() {
                        self.material.transmission_roughness = top.as_float();
                    }
                }
                NodeOp::MaterialEmission => {
                    if let Some(top) = self.stack.last() {
                        self.material.emission_color = top.as_vec3();
                    }
                }
            }
        }
    }

    /// Place a voxel box into the world. We first model into a separate grid
    /// and than merge back into the program grid.
    pub fn place(&mut self, id: &String, program: &mut Program) {
        let voxel = match program.voxels.get(id) {
            Some(defined) => defined.clone(),
            None => return,
        };

        let mut grid = VoxelGrid::empty(program.grid.read().unwrap().density);

        let mut execution = Execution::new_from_var(&self);

        let mut size = Vec3::new(1.0, 1.0, 1.0);
        execution.execute(&voxel.size, program);
        if let Some(value) = execution.stack.last() {
            size = value.as_vec3();
        }

        let rect = VoxelRect {
            origin: Vec3::zero(),
            size,
        };

        for world in rect.iter_voxels(&grid) {
            let local = rect.world_to_local(world);

            execution.stack.clear();

            // Set up the voxel coordinates
            execution.world = Value::from_vec3(world);
            execution.local = Value::from_vec3(local);

            // Inital bbox for the grid which the shapes adhere to and segments subdivide.
            execution.bbox = Aabb {
                min: -size / 2.0,
                max: size / 2.0,
            };

            // Execute the voxel body
            execution.execute(&voxel.body, program);

            // Recursively execute voxels shapes
            // for shape in voxel.shapes.iter() {
            //     shape.execute(&mut execution, program);
            // }

            // Set the result.
            if let Some(value) = execution.stack.last() {
                let mat = value.x();
                if mat >= 0.0 {
                    let hash = (execution.hash * 255.0).floor() as u8;
                    grid.set_create(world, Voxel::new(mat as u8, hash));
                }
            }
        }

        program.grid.write().unwrap().merge(&grid);
    }
}
