use crate::prelude::*;
pub mod execution;
pub mod program;
pub mod value;

#[derive(Debug, Clone)]
pub enum NodeOp {
    Load(usize),
    Store(usize),
    Component(u8),
    If(Vec<NodeOp>, Option<Vec<NodeOp>>),
    Place(String),
    Push(Value),
    World,
    Local,
    U,
    V,
    D,
    Pack3,
    Add,
    Sub,
    Mul,
    Div,
    Length,
    Abs,
    Sin,
    Cos,
    Tan,
    Floor,
    Ceil,
    Fract,
    Mod,
    Degrees,
    Radians,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    And,
    Or,
    Not,
    Neg,
    ShapeRect(Vec<NodeOp>),
    ShapeDisc(Vec<NodeOp>),
    SegmentLeft(Vec<NodeOp>),
    SegmentBack(Vec<NodeOp>),
    SegmentBottom(Vec<NodeOp>),
    PatternModulo(Option<Vec<NodeOp>>, Option<Vec<NodeOp>>),
}
